Repository xspec/xspec, pull requests merged in 2018-11, with the labels that each got.

#269 Run unit test for XQuery
  .travis.yml
  appveyor.yml
  src/ant/find-test-failure.xsl
  test/ant/.gitignore
  test/ant/README.md
  test/ant/build-worker_template.xml
  test/ant/build.xml
  test/ant/common/README.md
  test/ant/common/build-worker_util.xml
  test/ant/common/generate-build-worker.xsl
  test/ant/xspec.properties
  test/run-xspec-tests-ant.cmd
  test/run-xspec-tests-ant.sh
Labels: test

#279 Add Ant build support for code coverage
  build.xml
Labels: enhancement

#281 Add Ant build support for JUnit
  build.xml
  test/xspec-bat.cmd
  test/xspec.bats
Labels: enhancement

#464 Fix "find"-command in `xspec.bat`
  bin/xspec.bat
Labels: enhancement

#282 Fix issue 185 (Imported scenario order is unstable)
  src/compiler/generate-common-tests.xsl
  test/xspec-185/import-1.xspec
  test/xspec-185/import-2a.xspec
  test/xspec-185/import-2b.xspec
  test/xspec-185/import-3.xspec
  test/xspec-bat.cmd
  test/xspec.bats
Labels: bug
