Repository xspec/xspec, pull requests merged in 2019-11, with the labels that each got.

#696 Append -compiled to compiled query/stylesheet file name
  bin/xspec.bat
  bin/xspec.sh
  build.xml
  test/win-bats/collection.xml
  test/xspec-catch.xspec
  test/xspec.bats
Labels: enhancement

#698 Fix issue 697 (Empty document node is reported without XPath notation)
  src/compiler/generate-query-utils.xql
  src/compiler/generate-tests-utils.xsl
  src/reporter/format-xspec-report.xsl
  test/end-to-end/cases/expected/query/xspec-report-junit.xml
  test/end-to-end/cases/expected/query/xspec-report-result.html
  test/end-to-end/cases/expected/query/xspec-report-result.xml
  test/end-to-end/cases/expected/query/xspec-three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-report-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.html
  test/end-to-end/cases/xspec-report.xspec
Labels: bug

#703 Ant-based test: Parameterize query for fn:collection()
  test/ant/build.xml
  test/ant/worker/generate.xsl
Labels: test

#705 Fix #665 (Content of role attributes)
  .gitignore
  src/schematron/schut-to-xspec.xsl
  test/end-to-end/cases/expected/schematron/schematron-023-junit.xml
  test/end-to-end/cases/expected/schematron/schematron-023-result.html
  test/end-to-end/cases/expected/schematron/schematron-023-result.xml
  test/end-to-end/cases/schematron-023.xspec
  test/schematron/schematron-023.sch
  test/schematron/schut-to-xspec-012-out.xspec
Labels: enhancement

#706 ci: fix .travis.yml according to build config validation message
  .travis.yml
Labels: test

#591 Simplify handling of whitespace-only text nodes
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  src/schematron/schut-to-xspec.xsl
Labels: enhancement

#675 ci: codespell
  .travis.yml
  appveyor.yml
  src/compiler/generate-query-tests.xsl
  test/README
  test/ci/azure-pipelines_windows.yml
  test/ci/run-codespell.cmd
  test/ci/run-codespell.sh
  test/end-to-end/ant/generate-expected/worker/generate.xsl
  test/schut-to-xspec-012.sch
Labels: test

#708 Ignore Oxygen project file
  .gitignore
Labels: enhancement

#680 Remove EXPath file module from coverage-report.xsl
  bin/xspec.bat
  bin/xspec.sh
  build.xml
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.class
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.java
  src/reporter/coverage-report.xsl
Labels: enhancement

#712 Remove test/end-to-end/cases/schematron-01.xspec
  test/end-to-end/cases/expected/schematron/schematron-01-junit.xml
  test/end-to-end/cases/expected/schematron/schematron-01-result.html
  test/end-to-end/cases/expected/schematron/schematron-01-result.xml
  test/end-to-end/cases/schematron-01.xspec
Labels: test

#715 Test for issue 700 (Catch error messages from xsl:message terminate=yes)
  test/ant/worker/generate.xsl
  test/xspec-700.xml
  test/xspec-700.xsl
  test/xspec-700.xspec
Labels: test

#714 Detect Schematron in generate-xspec-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  test/sch-location-compare.xspec
Labels: enhancement

#704 Diff color of attributes and processing instructions
  src/reporter/format-utils.xsl
  test/end-to-end/cases/expected/query/xspec-452-result.html
  test/end-to-end/cases/expected/query/xspec-report-result.html
  test/end-to-end/cases/expected/query/xspec-serialize-junit.xml
  test/end-to-end/cases/expected/query/xspec-serialize-result.html
  test/end-to-end/cases/expected/query/xspec-serialize-result.xml
  test/end-to-end/cases/expected/query/xspec-three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-23_2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-452-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.html
  test/end-to-end/cases/xspec-serialize.xspec
Labels: enhancement

#717 Use Bats work dir by default
  test/run-bats.cmd
  test/run-bats.sh
  test/win-bats/collection.xml
  test/win-bats/stub.cmd
  test/xspec.bats
Labels: test

#718 ci: install test deps using 7z if tar not built in
  appveyor.yml
  test/ci/extract-tgz.cmd
  test/ci/extract-zip.cmd
  test/ci/install-deps.cmd
Labels: test

#721 Skip xspec-xmlns.xspec on Saxon 9.7
  test/ant/worker/generate.xsl
  test/xspec-xmlns.xspec
Labels: test

#722 Test with href strip-space=yes
  test/saxon-custom-options/config.xml
  test/saxon-custom-options/test.xspec
  test/saxon-custom-options/ws-only-text.xml
  test/win-bats/collection.xml
  test/xspec.bats
Labels: test

#723 Externalize whitespace-only text node functions
  src/common/xspec-utils.xsl
  src/compiler/generate-common-tests.xsl
  test/xspec-utils/parse-preserve-space.xspec
  test/xspec-utils_stylesheet.xspec
Labels: enhancement

#724 Merge test/catalog/catalog-01 and catalog-02
  test/catalog/01/catalog.xml
  test/catalog/01/example.dtd
  test/catalog/01/example.xml
  test/catalog/01/imported.xspec
  test/catalog/01/imported_schematron.xspec
  test/catalog/01/imported_stylesheet.xspec
  test/catalog/01/tested.sch
  test/catalog/01/tested.xquery
  test/catalog/01/tested.xsl
  test/catalog/02/imported-schematron.xspec
  test/catalog/02/imported-xquery.xspec
  test/catalog/02/imported-xslt.xspec
  test/catalog/02/test.xml
  test/catalog/02/tested.sch
  test/catalog/02/tested.xquery
  test/catalog/catalog-01-catalog.xml
  test/catalog/catalog-01-xquery.xspec
  test/catalog/catalog-01-xslt.xspec
  test/catalog/catalog-01.xquery
  test/catalog/catalog-01.xslt
  test/catalog/catalog-01_query.xspec
  test/catalog/catalog-01_schematron.xspec
  test/catalog/catalog-01_stylesheet.xspec
  test/catalog/catalog-02-catalog.xml
  test/catalog/catalog-02-schematron.xspec
  test/catalog/catalog-02-xquery.xspec
  test/catalog/catalog-02-xslt.xspec
  test/end-to-end/cases/expected/stylesheet/xspec-xslt2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-xslt2-result.xml
  test/win-bats/collection.xml
  test/xspec-xslt1.xspec
  test/xspec-xslt3.xspec
  test/xspec.bats
Labels: test

#719 Enable Schematron text node location
  src/schematron/generate-step3-wrapper.xsl
  src/schematron/patch-step3.xsl
  test/schematron-024.sch
  test/schematron-024.xspec
  test/xspec-396.xspec
Labels: enhancement

#725 Get xslt-version using a single function
  src/common/xspec-utils.xsl
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  src/schematron/generate-step3-wrapper.xsl
  test/xspec-utils_stylesheet.xspec
Labels: enhancement

#726 Color XPath expression diff in report HTML
  src/reporter/format-xspec-report.xsl
  test/end-to-end/cases/expected/query/xspec-177-result.html
  test/end-to-end/cases/expected/query/xspec-346-result.html
  test/end-to-end/cases/expected/query/xspec-452-result.html
  test/end-to-end/cases/expected/query/xspec-467-result.html
  test/end-to-end/cases/expected/query/xspec-67-result.html
  test/end-to-end/cases/expected/query/xspec-ambiguous-expect-result.html
  test/end-to-end/cases/expected/query/xspec-report-junit.xml
  test/end-to-end/cases/expected/query/xspec-report-result.html
  test/end-to-end/cases/expected/query/xspec-report-result.xml
  test/end-to-end/cases/expected/query/xspec-serialize-result.html
  test/end-to-end/cases/expected/query/xspec-three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/mode-all-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-177-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-23_2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-346-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-452-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-467-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-67-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-ambiguous-expect-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-report-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-result-naming-collision-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-rule-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-xslt2-result.html
  test/end-to-end/cases/xspec-report.xspec
Labels: enhancement

#727 Remove redundant -ext:on from build.xml
  build.xml
Labels: enhancement

#729 Remove namespace alias from generate-tests-helper.xsl
  src/compiler/generate-tests-helper.xsl
  src/schematron/generate-step3-wrapper.xsl
Labels: enhancement

#732 Locate Schematron file URI using a single function
  build.xml
  src/ant/locate-schematron-uri.xsl
  src/common/xspec-utils.xsl
  src/schematron/sch-file-path.xsl
  test/xspec-utils_stylesheet.xspec
Labels: enhancement

#713 Integrate Oxygen framework
  .gitignore
  editors/oxygen/.cvsignore
  editors/oxygen/README
  editors/oxygen/build.xml
  editors/oxygen/templates/xspec.xml
  editors/oxygen/xspec.framework
  xspec.framework
  xspec.xpr
Labels: enhancement

#736 Add Oxygen XQuery XProc transformation scenario
  xspec.framework
Labels: enhancement

#737 Add XQuery template for Oxygen
  templates/xquery.properties
  templates/xquery.xspec
Labels: enhancement

#745 Add Schematron template for Oxygen
  templates/schematron.properties
  templates/schematron.xspec
Labels: enhancement
