Repository xspec/xspec, pull requests merged in 2019-05, with the labels that each got.

#457 Make xspec-three-dots.xspec more portable
  test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.xml
  test/end-to-end/cases/xspec-three-dots.xsl
  test/end-to-end/cases/xspec-three-dots.xspec
Labels: test

#567 Increment version for v1.3.0 release
  pom.xml
Labels: release

#568 Increment version for v1.4.0 development
  pom.xml
Labels: release

#459 Fix issue 450 and 451 (XQuery text node containing curly bracket crashes)
  src/compiler/generate-query-helper.xsl
  test/end-to-end/cases/expected/query/xspec-450-451-junit.xml
  test/end-to-end/cases/expected/query/xspec-450-451-result.html
  test/end-to-end/cases/expected/query/xspec-450-451-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-450-451-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-450-451-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-450-451-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-450-451_stylesheet-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-450-451_stylesheet-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-450-451_stylesheet-result.xml
  test/end-to-end/cases/xspec-450-451.xml
  test/end-to-end/cases/xspec-450-451.xsl
  test/end-to-end/cases/xspec-450-451.xspec
  test/end-to-end/cases/xspec-450-451_stylesheet.xspec
  test/xspec-avt.xspec
Labels: bug

#460 Enable x:text on XQuery
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  test/xspec-space.xquery
  test/xspec-space_query.xspec
Labels: enhancement

#461 Fix issue 448 (XQuery scenario label containing curly bracket crashes)
  src/compiler/generate-query-helper.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  test/end-to-end/cases/expected/query/xspec-448-junit.xml
  test/end-to-end/cases/expected/query/xspec-448-result.html
  test/end-to-end/cases/expected/query/xspec-448-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-448-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-448-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-448-result.xml
  test/end-to-end/cases/xspec-448.xspec
Labels: bug

#462 Fix issue 449 (XQuery expect label containing curly bracket crashes)
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  test/end-to-end/cases/expected/query/xspec-449-junit.xml
  test/end-to-end/cases/expected/query/xspec-449-result.html
  test/end-to-end/cases/expected/query/xspec-449-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-449-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-449-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-449-result.xml
  test/end-to-end/cases/xspec-449.xspec
Labels: bug

#463 Fix issue 447 (Pending label containing curly bracket crashes)
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  test/end-to-end/cases/expected/query/xspec-447_1-junit.xml
  test/end-to-end/cases/expected/query/xspec-447_1-result.html
  test/end-to-end/cases/expected/query/xspec-447_1-result.xml
  test/end-to-end/cases/expected/query/xspec-447_2-junit.xml
  test/end-to-end/cases/expected/query/xspec-447_2-result.html
  test/end-to-end/cases/expected/query/xspec-447_2-result.xml
  test/end-to-end/cases/expected/query/xspec-447_3-junit.xml
  test/end-to-end/cases/expected/query/xspec-447_3-result.html
  test/end-to-end/cases/expected/query/xspec-447_3-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-447_1-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-447_1-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-447_1-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-447_2-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-447_2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-447_2-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-447_3-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-447_3-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-447_3-result.xml
  test/end-to-end/cases/xspec-447_1.xspec
  test/end-to-end/cases/xspec-447_2.xspec
  test/end-to-end/cases/xspec-447_3.xspec
Labels: bug

#465 Integrate unit-expect-xsl.xspec into generate-xspec-tests.xspec
  test/generate-xspec-tests.xspec
  test/schema/build.xml
  test/unit-expect-xsl.xspec
Labels: test

#469 Fix issue 468 (XSLT and XQuery different attribute(date) in XML report)
  src/compiler/generate-query-tests.xsl
  test/end-to-end/processor/xml/_normalizer.xsl
Labels: bug

#470 Fix issue 467 (Namespace of the same prefix is dropped from HTML report)
  src/reporter/format-utils.xsl
  test/end-to-end/cases/expected/query/xspec-467-junit.xml
  test/end-to-end/cases/expected/query/xspec-467-result.html
  test/end-to-end/cases/expected/query/xspec-467-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-467-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-467-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-467-result.xml
  test/end-to-end/cases/xspec-467.xspec
Labels: bug

#471 Fix issue 392 (Move oXygen documentation from build.xml to Wiki)
  build.xml
Labels: documentation

#472 Fix issue 466 (XSpec occupies x: namespace prefix)
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  test/end-to-end/cases/expected/query/xspec-focus-1-result.xml
  test/end-to-end/cases/expected/query/xspec-function-result.xml
  test/end-to-end/cases/expected/query/xspec-import-result.xml
  test/end-to-end/cases/expected/query/xspec-imported-result.xml
  test/end-to-end/cases/expected/query/xspec-pending-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-focus-1-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-focus-1-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-function-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-function-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-import-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-import-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-imported-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-pending-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-pending-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-rule-result.xml
  test/end-to-end/cases/xspec-focus-1.xspec
  test/end-to-end/cases/xspec-function.xspec
  test/end-to-end/cases/xspec-import.xspec
  test/end-to-end/cases/xspec-pending.xspec
  test/generate-tests-utils.xspec
  test/generate-xspec-tests.xspec
  test/xspec-eqname.xspec
  test/xspec-prefix-conflict.xquery
  test/xspec-prefix-conflict.xsl
  test/xspec-prefix-conflict.xspec
  test/xspec-prefix-conflict_stylesheet.xspec
  test/xspec-uri.xspec
Labels: bug

#473 Schema: Remove redundant xs declaration
  src/schemas/xspec.rnc
Labels: enhancement

#474 Update test deps (as of 2018-12-04Z)
  .travis.yml
  appveyor.yml
Labels: test

#476 Test attribute(shared) and x:like
  test/end-to-end/cases/expected/query/xspec-shared-like-junit.xml
  test/end-to-end/cases/expected/query/xspec-shared-like-result.html
  test/end-to-end/cases/expected/query/xspec-shared-like-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-shared-like-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-shared-like-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-shared-like-result.xml
  test/end-to-end/cases/xspec-shared-like.xspec
Labels: test

#478 Update test deps (as of 2018-12-24Z)
  .travis.yml
  appveyor.yml
Labels: test
