Repository xspec/xspec, pull requests merged in 2019-01, with the labels that each got.

#499 Update readme
  README.md
Labels: documentation

#304 Comment out pending invalid scenario in xspec-rule.xspec
  test/end-to-end/cases/expected/xspec-rule-junit-norm.xml
  test/end-to-end/cases/expected/xspec-rule-result-norm.html
  test/end-to-end/cases/xspec-rule.xspec
Labels: test

#305 Include test/end-to-end/cases/ in schema validation test
  test/win-bats/collection.xml
  test/xspec.bats
Labels: test

#306 Include tutorial/coverage/ in schema validation test
  test/win-bats/collection.xml
  test/xspec.bats
Labels: test

#307 Schema: Move node-selection's href and user-content into choice
  src/schemas/xspec.rnc
  test/win-bats/collection.xml
  test/xspec-node-selection.xml
  test/xspec-node-selection.xsl
  test/xspec-node-selection.xspec
  test/xspec.bats
Labels: enhancement

#415 added java/ path to compiler, and Saxon dependency, to compiler XSLTC…
  pom.xml
Labels: bug

#309 Warn if x:expect is ambiguous (node-selection with boolean test attribute)
  src/compiler/generate-xspec-tests.xsl
  test/end-to-end/cases/expected/xspec-ambiguous-expect-junit-norm.xml
  test/end-to-end/cases/expected/xspec-ambiguous-expect-result-norm.html
  test/end-to-end/cases/xspec-ambiguous-expect.xml
  test/end-to-end/cases/xspec-ambiguous-expect.xspec
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#310 Test mode=x:setup-context
  test/xspec-setup-context.xml
  test/xspec-setup-context.xsl
  test/xspec-setup-context.xspec
Labels: test

#312 Fix issue 308 (x:label affects expectation) for XSLT
  src/compiler/generate-xspec-tests.xsl
  test/end-to-end/cases/expected/xspec-ambiguous-expect-junit-norm.xml
  test/end-to-end/cases/expected/xspec-ambiguous-expect-result-norm.html
  test/end-to-end/cases/xspec-ambiguous-expect.xspec
  test/end-to-end/cases/xspec-three-dots.xspec
  test/xspec-308.xml
  test/xspec-308.xspec
Labels: bug

#313 Define version and xslt-version attributes as decimal
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-utils.xql
  src/compiler/generate-tests-utils.xsl
  src/compiler/generate-xspec-tests.xsl
  src/schemas/xspec.rnc
Labels: enhancement

#314 Update test deps (as of 2018-08-30Z)
  .travis.yml
  appveyor.yml
Labels: test

#315 Fix issue 67 (Cannot compare namespace node)
  src/compiler/generate-tests-utils.xsl
  test/end-to-end/cases/expected/xspec-67-junit-norm.xml
  test/end-to-end/cases/expected/xspec-67-result-norm.html
  test/end-to-end/cases/expected/xspec-three-dots-junit-norm.xml
  test/end-to-end/cases/expected/xspec-three-dots-result-norm.html
  test/end-to-end/cases/xspec-67.xspec
  test/end-to-end/cases/xspec-three-dots.xspec
  test/generate-tests-utils.xspec
  test/items.xsl
Labels: bug

#316 Do not include generate-tests-utils.xsl twice in generate-x-utils.xspec
  test/generate-x-utils.xspec
Labels: test

#317 Fix issue 59 (x:expect/@test terminates when function or template returns attribute)
  src/compiler/generate-tests-utils.xsl
  src/compiler/generate-xspec-tests.xsl
  test/generate-tests-utils.xspec
  test/items.xsl
  test/xspec-59.xspec
  test/xspec-59_use-case-1.xsl
  test/xspec-59_use-case-1.xspec
  test/xspec-59_use-case-2.xsl
  test/xspec-59_use-case-2.xspec
Labels: bug

#318 Restore test file format
  test/end-to-end/cases/xspec-focus-1.xspec
  test/end-to-end/cases/xspec-function.xspec
  test/end-to-end/cases/xspec-import.xspec
  test/end-to-end/cases/xspec-imported.xspec
  test/end-to-end/cases/xspec-pending.xspec
  test/end-to-end/cases/xspec-rule.xspec
  test/generate-tests-utils.xspec
  test/generate-x-utils.xspec
  test/generate-xspec-tests.xspec
  test/unit-expect-xsl.xspec
  test/xspec-focus-2.xspec
  test/xspec-variable.xspec
  tutorial/escape-for-regex.xspec
Labels: test

#319 Fix issue 153 (Test terminates with XPTY0004 in defining $impl:successful)
  src/compiler/generate-xspec-tests.xsl
  test/end-to-end/cases/expected/xspec-153-junit-norm.xml
  test/end-to-end/cases/expected/xspec-153-result-norm.html
  test/end-to-end/cases/xspec-153.xspec
Labels: bug

#508 Move Compilation.md from Wiki
  tutorial/under-the-hood/Compilation.md
  tutorial/under-the-hood/README.md
Labels: documentation
