Repository xspec/xspec, pull requests merged in 2019-10, with the labels that each got.

#660 Add xsl:context-item to named templates
  src/common/xspec-utils.xsl
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-helper.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-tests-utils.xsl
  src/compiler/generate-xspec-tests.xsl
  src/reporter/coverage-report.xsl
  src/reporter/format-utils.xsl
  src/reporter/format-xspec-report-folding.xsl
  src/reporter/format-xspec-report.xsl
  src/schematron/schut-to-xspec.xsl
  test/ant/worker/generate.xsl
  test/end-to-end/ant/base/worker/generate.xsl
  test/end-to-end/ant/generate-expected/worker/generate.xsl
  test/end-to-end/ant/run-e2e-tests/worker/generate.xsl
  test/end-to-end/processor/base/_normalizer.xsl
  test/end-to-end/processor/html/_normalizer.xsl
  test/win-bats/generate.xsl
Labels: enhancement

#664 ci: test Maven package and fix javadoc compatibility with JDK 11
  .travis.yml
  appveyor.yml
  pom.xml
  test/ci/azure-pipelines_windows.yml
  test/ci/maven-package.cmd
  test/ci/maven-package.sh
Labels: test

#657 Fix test/end-to-end/cases/xspec-shared-like.xspec
  test/end-to-end/cases/expected/query/xspec-shared-like-junit.xml
  test/end-to-end/cases/expected/query/xspec-shared-like-result.html
  test/end-to-end/cases/expected/query/xspec-shared-like-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-shared-like-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-shared-like-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-shared-like-result.xml
  test/end-to-end/cases/xspec-shared-like.xspec
Labels: test

#658 Test inheritance in x:copy-namespaces()
  test/xspec-utils_stylesheet.xspec
Labels: test

#644 Fix Ant issue 633 (Nashorn engine is deprecated)
  build.xml
  java/io/xspec/xspec/ant/taskdefs/MakePath.class
  java/io/xspec/xspec/ant/taskdefs/MakePath.java
  pom.xml
  src/ant/make-path.js
  test/ci/build_java.xml
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#668 'fail' and 'cleanup' in 'depends', not as <antcall>
  build.xml
  test/win-bats/collection.xml
  test/xspec.bats
Labels: bug

#667 ci: externalize *nix tests further
  .travis.yml
  azure-pipelines.yml
  test/ci/compile-java.sh
  test/ci/last-git-status.sh
  test/ci/maven-package.sh
  test/ci/run-core-tests.sh
  test/run-bats.sh
  test/run-xspec-tests-ant.sh
Labels: test

#661 Replace mode=x:copy-namespaces template with function
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
Labels: enhancement

#673 ci: replace .travis.yml before_script with install
  .travis.yml
Labels: test

#671 Replace Ant import with include
  test/ant/worker/build-worker_template.xml
  test/ant/worker/build-worker_util.xml
  test/end-to-end/ant/base/build.xml
  test/end-to-end/ant/base/worker/build-worker.xml
  test/end-to-end/ant/generate-expected/build.xml
  test/end-to-end/ant/generate-expected/worker/build-worker_template.xml
  test/end-to-end/ant/run-e2e-tests/build.xml
  test/end-to-end/ant/run-e2e-tests/worker/build-worker_template.xml
Labels: test

#674 ci: unset JVM environment variables in run-bats.sh
  .travis.yml
  test/run-bats.sh
Labels: test

#677 Move test/ant/caps/* to test/caps/*
  test/ant/build.xml
  test/caps/schema-aware.xquery
  test/caps/schema-aware.xsd
  test/caps/v3-0.xsl
  test/caps/v3-1.xquery
  test/run-bats.cmd
  test/run-bats.sh
Labels: test

#678 ci: enable Maven package test on AppVeyor
  appveyor.yml
Labels: test

#676 Test importing Ant build file
  test/ant-import/build.xml
  test/win-bats/collection.xml
  test/xspec.bats
Labels: test

#663 Fix issue 655 (Coverage report loses hit when output dir is specified)
  bin/xspec.bat
  bin/xspec.sh
  build.xml
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.class
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.java
  test/ant/worker/build-worker_util.xml
  test/win-bats/collection.xml
  test/xspec.bats
Labels: bug

#662 Paler diff color when element QName is equal
  src/reporter/format-utils.xsl
  src/reporter/test-report.css
  test/end-to-end/cases/expected/query/xspec-346-result.html
  test/end-to-end/cases/expected/query/xspec-467-result.html
  test/end-to-end/cases/expected/query/xspec-serialize-result.html
  test/end-to-end/cases/expected/query/xspec-three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-23_2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-346-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-467-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.html
Labels: enhancement

#684 Fix issue 682 (Module URIs in coverage report HTML are not formatted)
  src/reporter/coverage-report.xsl
Labels: bug

#686 ci: invalidate preinstalled Ant
  test/ci/install-deps.cmd
  test/ci/install-deps.sh
Labels: test

#687 ci: test with XML Calabash 1.1.29
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  test/ci/azure-pipelines_windows.yml
Labels: test

#683 Fix issue 681 (Leading slash missing from formatted URI in HTML report on *nix)
  src/common/xspec-utils.xsl
  src/reporter/coverage-report.xsl
  src/reporter/format-utils.xsl
  src/reporter/format-xspec-report.xsl
  test/xspec-utils_stylesheet.xspec
Labels: bug

#640 Bug fix: Recognize namespace declarations on descendants of x:description, for XSLT testing
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-tests-helper.xsl
  src/compiler/generate-xspec-tests.xsl
  src/schematron/generate-step3-wrapper.xsl
  test/xspec-prefix-conflict-local.xspec
  test/xspec-prefix-parent-vs-import.xspec
  test/xspec-xmlns-imported.xspec
  test/xspec-xmlns.sch
  test/xspec-xmlns.xsl
  test/xspec-xmlns.xspec
  test/xspec-xmlns_schematron.xspec
Labels: bug

#694 Fix issue 693 (end-to-end test cannot handle svrl:active-pattern/attribute(document) if it's zero-length)
  test/end-to-end/cases/expected/schematron/xspec-693-junit.xml
  test/end-to-end/cases/expected/schematron/xspec-693-result.html
  test/end-to-end/cases/expected/schematron/xspec-693-result.xml
  test/end-to-end/cases/xspec-693.sch
  test/end-to-end/cases/xspec-693.xspec
  test/end-to-end/processor/xml/_normalizer.xsl
Labels: test

#688 Detect x:like errors
  src/compiler/generate-common-tests.xsl
  test/like/loop.xspec
  test/like/multiple.xspec
  test/like/none.xspec
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#690 Fix issue 689 (Namespace and attribute nodes are serialized with misaligned indentation)
  src/reporter/format-utils.xsl
  test/end-to-end/cases/expected/query/xspec-467-result.html
  test/end-to-end/cases/expected/query/xspec-serialize-junit.xml
  test/end-to-end/cases/expected/query/xspec-serialize-result.html
  test/end-to-end/cases/expected/query/xspec-serialize-result.xml
  test/end-to-end/cases/expected/schematron/xspec-693-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-23_2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-467-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.xml
  test/end-to-end/cases/xspec-serialize.xspec
Labels: bug

#699 Test for serialization color of attribute and processing insturction
  test/end-to-end/cases/expected/query/xspec-serialize-junit.xml
  test/end-to-end/cases/expected/query/xspec-serialize-result.html
  test/end-to-end/cases/expected/query/xspec-serialize-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.xml
  test/end-to-end/cases/xspec-serialize.xspec
Labels: test
