Repository xspec/xspec, pull requests merged in 2019-12, with the labels that each got.

#747 ci: test with XML Calabash 1.1.30
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  test/ci/azure-pipelines_windows.yml
Labels: test

#748 Fix typo in code comment
  test/xspec-utils/parse-preserve-space.xspec
Labels: bug, test

#743 Publish XSpec development version as Oxygen add-on
  editors/oxygen/add-on/description/0-0-1.xhtml
  editors/oxygen/add-on/description/latest.xhtml
  oxygen-addon.xml
Labels: enhancement, release

#739 Support XQuery in Run XSpec Test transformation scenario
  xspec.framework
Labels: enhancement

#738 Add Oxygen transformation scenario for Code Coverage
  xspec.framework
Labels: enhancement

#751 Oxygen add-on v0.0.3
  editors/oxygen/add-on/description/0-0-1.xhtml
  editors/oxygen/add-on/description/latest.xhtml
  oxygen-addon.xml
Labels: release

#749 ci: test with Saxon 9.9.1.6
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  test/ant/worker/generate.xsl
  test/ci/azure-pipelines_windows.yml
  test/xspec-700.xspec
Labels: test

#752 release: remove SNAPSHOT from version in pom.xml
  pom.xml
Labels: release

#754 release: increment pom.xml
  pom.xml
Labels: release

#755 release: oxygen add-on v0.0.4
  editors/oxygen/add-on/description/latest.xhtml
  oxygen-addon.xml
Labels: release
