Repository xspec/xspec, pull requests merged in 2019-07, with the labels that each got.

#518 Save normalized report using its file name extension
  src/common/xspec-utils.xsl
  test/end-to-end/processor/base/compare.xsl
  test/xspec-utils_stylesheet.xspec
Labels: bug, test

#519 Test for function-param position
  test/xspec-param-position.xspec
Labels: test

#523 xml-stylesheet processing instruction in XQuery report XML
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  test/end-to-end/cases/expected/query/xspec-153-result.xml
  test/end-to-end/cases/expected/query/xspec-177-result.xml
  test/end-to-end/cases/expected/query/xspec-346-result.xml
  test/end-to-end/cases/expected/query/xspec-447_1-result.xml
  test/end-to-end/cases/expected/query/xspec-447_2-result.xml
  test/end-to-end/cases/expected/query/xspec-447_3-result.xml
  test/end-to-end/cases/expected/query/xspec-448-result.xml
  test/end-to-end/cases/expected/query/xspec-449-result.xml
  test/end-to-end/cases/expected/query/xspec-450-451-result.xml
  test/end-to-end/cases/expected/query/xspec-452-result.xml
  test/end-to-end/cases/expected/query/xspec-467-result.xml
  test/end-to-end/cases/expected/query/xspec-67-result.xml
  test/end-to-end/cases/expected/query/xspec-ambiguous-expect-result.xml
  test/end-to-end/cases/expected/query/xspec-focus-1-result.xml
  test/end-to-end/cases/expected/query/xspec-function-result.xml
  test/end-to-end/cases/expected/query/xspec-import-result.xml
  test/end-to-end/cases/expected/query/xspec-imported-result.xml
  test/end-to-end/cases/expected/query/xspec-pending-result.xml
  test/end-to-end/cases/expected/query/xspec-report-result.xml
  test/end-to-end/cases/expected/query/xspec-serialize-result.xml
  test/end-to-end/cases/expected/query/xspec-shared-like-result.xml
  test/end-to-end/cases/expected/query/xspec-three-dots-result.xml
Labels: enhancement

#525 Simplify test:report-sequence() test param
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-query-utils.xql
  src/compiler/generate-tests-utils.xsl
  src/compiler/generate-xspec-tests.xsl
Labels: enhancement

#527 Update annotations for xspec.result.html and xspec.coverage.html Ant properties
  build.xml
Labels: documentation

#529 Fix issue 528 (Failure report is not available in HTML when focusing on a child scenario)
  src/reporter/format-xspec-report.xsl
  test/end-to-end/cases/expected/stylesheet/xspec-528-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-528-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-528-result.xml
  test/end-to-end/cases/xspec-528.xspec
Labels: bug

#582 Noting CSS difference between actual and expected
  test/end-to-end/README.md
Labels: documentation

#530 Parse XML report using common functions
  src/ant/find-test-failure.xsl
  src/common/parse-report.xsl
  src/reporter/format-xspec-report-folding.xsl
  src/reporter/format-xspec-report.xsl
  src/reporter/junit-report.xsl
Labels: enhancement

#531 Make xspec-space_stylesheet.xspec more portable
  test/xspec-space.xsl
  test/xspec-space_stylesheet.xspec
Labels: test

#532 Merge xspec-space_*.xspec
  test/xspec-space.xquery
  test/xspec-space.xspec
  test/xspec-space_stylesheet.xspec
Labels: test

#533 Explicit error message when source doc is not an XSpec file
  src/compiler/generate-common-tests.xsl
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#534 Fix issue 78 (ID in report HTML is not unique)
  src/reporter/format-xspec-report.xsl
  test/end-to-end/cases/expected/query/xspec-153-result.html
  test/end-to-end/cases/expected/query/xspec-177-result.html
  test/end-to-end/cases/expected/query/xspec-346-result.html
  test/end-to-end/cases/expected/query/xspec-452-result.html
  test/end-to-end/cases/expected/query/xspec-467-result.html
  test/end-to-end/cases/expected/query/xspec-67-result.html
  test/end-to-end/cases/expected/query/xspec-focus-1-result.html
  test/end-to-end/cases/expected/query/xspec-function-result.html
  test/end-to-end/cases/expected/query/xspec-import-result.html
  test/end-to-end/cases/expected/query/xspec-imported-result.html
  test/end-to-end/cases/expected/query/xspec-pending-result.html
  test/end-to-end/cases/expected/query/xspec-report-result.html
  test/end-to-end/cases/expected/query/xspec-serialize-result.html
  test/end-to-end/cases/expected/query/xspec-three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-151-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-153-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-177-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-23_2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-346-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-452-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-467-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-50-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-55-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-67-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-focus-1-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-function-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-import-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-imported-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-pending-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-result-naming-collision-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-rule-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.html
  test/end-to-end/processor/html/_normalizer.xsl
Labels: bug

#535 Fix issue 85 (Useless href in report HTML)
  src/reporter/format-xspec-report.xsl
  test/end-to-end/cases/expected/query/xspec-447_1-result.html
  test/end-to-end/cases/expected/query/xspec-447_2-result.html
  test/end-to-end/cases/expected/query/xspec-447_3-result.html
  test/end-to-end/cases/expected/query/xspec-focus-1-result.html
  test/end-to-end/cases/expected/query/xspec-pending-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-447_1-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-447_2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-447_3-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-focus-1-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-pending-result.html
  test/end-to-end/processor/html/_normalizer.xsl
Labels: bug

#536 Highlight entire test block on click in HTML report
  src/reporter/format-xspec-report.xsl
  test/end-to-end/cases/expected/query/xspec-153-result.html
  test/end-to-end/cases/expected/query/xspec-177-result.html
  test/end-to-end/cases/expected/query/xspec-346-result.html
  test/end-to-end/cases/expected/query/xspec-452-result.html
  test/end-to-end/cases/expected/query/xspec-467-result.html
  test/end-to-end/cases/expected/query/xspec-67-result.html
  test/end-to-end/cases/expected/query/xspec-ambiguous-expect-result.html
  test/end-to-end/cases/expected/query/xspec-focus-1-result.html
  test/end-to-end/cases/expected/query/xspec-function-result.html
  test/end-to-end/cases/expected/query/xspec-import-result.html
  test/end-to-end/cases/expected/query/xspec-imported-result.html
  test/end-to-end/cases/expected/query/xspec-pending-result.html
  test/end-to-end/cases/expected/query/xspec-report-result.html
  test/end-to-end/cases/expected/query/xspec-serialize-result.html
  test/end-to-end/cases/expected/query/xspec-three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-151-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-153-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-177-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-23_2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-346-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-452-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-467-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-50-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-528-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-55-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-67-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-ambiguous-expect-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-focus-1-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-function-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-import-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-imported-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-pending-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-result-naming-collision-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-rule-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-xslt2-result.html
Labels: enhancement

#537 Highlight entire scenario block on click in HTML report
  src/reporter/format-xspec-report.xsl
  test/end-to-end/cases/expected/query/xspec-153-result.html
  test/end-to-end/cases/expected/query/xspec-177-result.html
  test/end-to-end/cases/expected/query/xspec-346-result.html
  test/end-to-end/cases/expected/query/xspec-452-result.html
  test/end-to-end/cases/expected/query/xspec-467-result.html
  test/end-to-end/cases/expected/query/xspec-67-result.html
  test/end-to-end/cases/expected/query/xspec-ambiguous-expect-result.html
  test/end-to-end/cases/expected/query/xspec-focus-1-result.html
  test/end-to-end/cases/expected/query/xspec-function-result.html
  test/end-to-end/cases/expected/query/xspec-import-result.html
  test/end-to-end/cases/expected/query/xspec-imported-result.html
  test/end-to-end/cases/expected/query/xspec-pending-result.html
  test/end-to-end/cases/expected/query/xspec-report-result.html
  test/end-to-end/cases/expected/query/xspec-serialize-result.html
  test/end-to-end/cases/expected/query/xspec-three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-151-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-153-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-177-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-23_2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-346-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-452-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-467-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-50-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-528-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-55-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-67-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-ambiguous-expect-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-focus-1-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-function-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-import-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-imported-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-pending-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-result-naming-collision-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-rule-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-xslt2-result.html
Labels: enhancement

#540 Update test deps (as of 2019-03-12Z)
  .travis.yml
  appveyor.yml
Labels: test

#576 Restore format of basex-standalone-xquery-harness.xproc
  src/harnesses/basex/basex-standalone-xquery-harness.xproc
Labels: enhancement

#541 Replace -xsl with -a in CLI formatting HTML
  bin/xspec.bat
  bin/xspec.sh
Labels: enhancement

#543 Test XQuery, Ant and catalog
  test/catalog/catalog-02-catalog.xml
  test/catalog/catalog-02-schematron.xspec
  test/catalog/catalog-02-xquery.xspec
  test/catalog/catalog-02-xslt.xspec
  test/win-bats/collection.xml
  test/xspec.bats
Labels: test

#544 Fix issue 542 (Fails to resolve URI on Windows when imported via catalog)
  src/common/xspec-utils.xsl
  src/compiler/generate-common-tests.xsl
  test/catalog/02/imported-schematron.xspec
  test/catalog/02/imported-xquery.xspec
  test/catalog/02/imported-xslt.xspec
  test/catalog/02/test.xml
  test/catalog/02/tested.sch
  test/catalog/02/tested.xquery
  test/catalog/02/tested.xsl
  test/catalog/catalog-02-catalog.xml
  test/catalog/catalog-02-schematron.xspec
  test/catalog/catalog-02-xquery.xspec
  test/catalog/catalog-02-xslt.xspec
  test/win-bats/collection.xml
  test/xspec-utils_stylesheet.xspec
  test/xspec.bats
  tutorial/schematron/demo-04.xspec
Labels: bug

#545 Fix issue 161 (Fails to test imported Schematron XSpec with href)
  src/schematron/schut-to-xspec.xsl
  test/catalog/02/imported-schematron.xspec
  test/schematron/schut-to-xspec-006-out.xspec
  test/schematron/schut-to-xspec-007-out.xspec
  test/schematron/schut-to-xspec-010-out.xspec
  test/schematron/schut-to-xspec-012-out.xspec
  test/schut-to-xspec.xspec
Labels: bug

#546 Report array and map content
  src/compiler/generate-query-utils.xql
  src/compiler/generate-tests-utils.xsl
  test/end-to-end/cases/expected/query/xspec-report-junit.xml
  test/end-to-end/cases/expected/query/xspec-report-result.html
  test/end-to-end/cases/expected/query/xspec-report-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-report-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-report-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report-result.xml
  test/end-to-end/cases/xspec-report.xspec
Labels: enhancement

#549 Fix issue 547 (Schematron ignores context select) and 548 (Schematron ignores AVT)
  bin/xspec.bat
  bin/xspec.sh
  build.xml
  src/schematron/schut-to-xspec.xsl
  test/schematron/schut-to-xspec-008-out.xspec
  test/schut-to-xspec.xspec
  test/xspec-547.sch
  test/xspec-547.xspec
  test/xspec-avt.sch
  test/xspec-avt_schematron.xspec
Labels: bug

#550 Wrap Schematron command lines in bin/xspec.*
  bin/xspec.bat
  bin/xspec.sh
Labels: enhancement

#551 Align CLI's Schematron wording with Ant's
  bin/xspec.bat
  bin/xspec.sh
  build.xml
  test/end-to-end/cases/expected/schematron/schematron-01-result.xml
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#552 Create Schematron XSpec in output dir
  bin/xspec.bat
  bin/xspec.sh
  build.xml
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#553 Test for issue 151 (Test terminates with FOTY0012 in test:report-sequence) on XQuery
  test/ant/build.xml
  test/ant/caps/schema-aware.xquery
  test/ant/caps/schema-aware.xsd
  test/ant/caps/v3-1.xquery
  test/ant/worker/generate.xsl
  test/end-to-end/cases/expected/query/xspec-151-junit.xml
  test/end-to-end/cases/expected/query/xspec-151-result.html
  test/end-to-end/cases/expected/query/xspec-151-result.xml
  test/end-to-end/cases/xspec-151.xml
  test/end-to-end/cases/xspec-151.xquery
  test/end-to-end/cases/xspec-151.xsd
  test/end-to-end/cases/xspec-151.xsl
  test/end-to-end/cases/xspec-151.xspec
Labels: test

#554 Update test deps (as of 2019-03-21Z)
  .travis.yml
  appveyor.yml
  test/win-bats/collection.xml
  test/xspec.bats
Labels: test

#556 Update comments for xspec.schematron.preprocessor.step* Ant properties
  build.xml
Labels: documentation

#558 Update test deps (as of 2019-04-04Z)
  .travis.yml
  appveyor.yml
Labels: test

#560 Test the pending scenario labels in xspec-focus-2.xspec
  test/end-to-end/cases/expected/query/xspec-focus-2-junit.xml
  test/end-to-end/cases/expected/query/xspec-focus-2-result.html
  test/end-to-end/cases/expected/query/xspec-focus-2-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-focus-2-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-focus-2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-focus-2-result.xml
  test/end-to-end/cases/xspec-focus-2.xspec
Labels: test

#561 Make focus and pending attributes unique in xspec-focus-1, xspec-focus-2 and xspec-pending.xspec
  test/end-to-end/cases/expected/query/xspec-focus-1-junit.xml
  test/end-to-end/cases/expected/query/xspec-focus-1-result.html
  test/end-to-end/cases/expected/query/xspec-focus-1-result.xml
  test/end-to-end/cases/expected/query/xspec-focus-2-junit.xml
  test/end-to-end/cases/expected/query/xspec-focus-2-result.html
  test/end-to-end/cases/expected/query/xspec-focus-2-result.xml
  test/end-to-end/cases/expected/query/xspec-pending-junit.xml
  test/end-to-end/cases/expected/query/xspec-pending-result.html
  test/end-to-end/cases/expected/query/xspec-pending-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-focus-1-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-focus-1-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-focus-1-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-focus-2-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-focus-2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-focus-2-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-pending-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-pending-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-pending-result.xml
  test/end-to-end/cases/xspec-focus-1.xspec
  test/end-to-end/cases/xspec-focus-2.xspec
  test/end-to-end/cases/xspec-pending.xspec
Labels: test

#562 Fix issue 393 (x:call-scenarios template references 'this' element)
  src/compiler/generate-common-tests.xsl
Labels: bug

#565 Fix issue 412 (select with href or child node always sorts nodes and eliminates duplicates) for XQuery
  src/compiler/generate-query-helper.xsl
  test/xspec-412.xspec
  test/xspec-412_stylesheet.xspec
Labels: bug

#566 Replace test/end-to-end/cases/schematron-01.* with x:import
  test/end-to-end/cases/expected/schematron/schematron-01-result.html
  test/end-to-end/cases/expected/schematron/schematron-01-result.xml
  test/end-to-end/cases/schematron-01.sch
  test/end-to-end/cases/schematron-01.xml
  test/end-to-end/cases/schematron-01.xspec
Labels: test

#571 Add test and comment for handling whitespace-only text node
  src/compiler/generate-query-helper.xsl
  src/compiler/generate-tests-helper.xsl
  test/xspec-space.xspec
Labels: documentation, test

#574 Update test deps (as of 2019-05-16Z)
  .travis.yml
  appveyor.yml
Labels: test

#581 Update test deps (as of 2019-07-02Z)
  .travis.yml
  appveyor.yml
Labels: test

#585 Set dist trusty in .travis.yml
  .travis.yml
Labels: test

#539 Fix typo 'inherrit' in schematron-012.xspec
  test/schematron-012.xspec
  test/schematron/schut-to-xspec-012-out.xspec
Labels: bug, test

#557 Simplify test:disable-escaping characters
  src/reporter/format-utils.xsl
Labels: enhancement

#564 Address SXWN9000 (child::div) in schut-to-xspec-012.sch
  test/schut-to-xspec-012.sch
Labels: test
