Repository xspec/xspec, pull requests merged in 2020-01, with the labels that each got.

#757 docs: Fill in a missing word in main Readme
  README.md
Labels: documentation

#758 ci: use HTTPS for fetching Maven files
  test/ci/install-deps.cmd
  test/ci/install-deps.sh
Labels: test

#672 docs: move and document find-examples.*
  misc/find-examples/README.md
  misc/find-examples/docs/doc1.xml
  misc/find-examples/docs/doc2.xml
  misc/find-examples/find-examples.rnc
  misc/find-examples/find-examples.xml
  misc/find-examples/find-examples.xsl
Labels: documentation

#756 docs: add contributing guidelines
  .dependabot/config.yml
  CONTRIBUTING.md
Labels: documentation

#679 refactor(schematron): create Schematron XSLT in output dir
  bin/xspec.bat
  bin/xspec.sh
  build.xml
  src/schematron/generate-step3-wrapper.xsl
  src/schematron/locate-schematron-uri.xsl
  src/schematron/patch-step3.xsl
  src/schematron/sch-file-path.xsl
  test/end-to-end/cases/expected/schematron/schematron-023-result.xml
  test/end-to-end/cases/expected/schematron/xspec-693-result.xml
  test/end-to-end/processor/xml/_normalizer.xsl
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#764 fix(report): sort namespace nodes in HTML report
  CONTRIBUTING.md
  src/reporter/format-utils.xsl
  test/end-to-end/cases/expected/query/xspec-467-result.html
  test/end-to-end/cases/expected/query/xspec-serialize-result.html
  test/end-to-end/cases/expected/schematron/schematron-023-result.html
  test/end-to-end/cases/expected/schematron/xspec-693-result.html
Labels: bug

#765 docs: add link to contributing guidelines
  README.md
Labels: documentation

#759 fix(basex): add explicit content encoding for HTML report
  src/harnesses/basex/basex-server-xquery-harness.xproc
  src/harnesses/basex/basex-standalone-xquery-harness.xproc
  test/win-bats/collection.xml
  test/xspec.bats
Labels: bug
