Repository xspec/xspec, pull requests merged in 2020-08, with the labels that each got.

#1116 fix: do not force inheriting global namespaces
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  test/end-to-end/cases/expected/query/import-result.xml
  test/end-to-end/cases/expected/stylesheet/format-xspec-report-folding-result.xml
  test/end-to-end/cases/expected/stylesheet/import-result.xml
Labels: bug

#1124 docs(schema): fix a typo 'paraemeters'
  src/schemas/xspec.rnc
Labels: bug, documentation

#1126 test: relocate test for redefining variable while mixing notations
  test/eqname.xspec
  test/variable.xspec
Labels: test

#1129 ci: support filtering Windows Bats-like tests
  test/.gitignore
  test/run-bats.cmd
  test/win-bats/generate.xsl
  test/win-bats/stub.cmd
Labels: test

#1131 ci: install test deps in parallel
  test/ci/build_install-deps.xml
Labels: test

#1132 ci(maven): ensure built-in class files are deleted before jar test
  test/ci/build_test-maven-jar.xml
Labels: test

#1134 docs: update a comment about transform cache=false
  src/compiler/generate-xspec-tests.xsl
Labels: documentation

#1130 feat: force focus on demand in Ant build
  build.xml
  src/compiler/generate-common-tests.xsl
  src/reporter/format-xspec-report-folding.xsl
  src/reporter/format-xspec-report.xsl
  test/ant/worker/build-worker_util.xml
  test/ant/worker/generate.xsl
  test/ci/build_install-deps.xml
  test/ci/env/README.md
  test/ci/print-env.cmd
  test/ci/print-env.sh
  test/end-to-end/cases/expected/query/force-focus_focus-1-junit.xml
  test/end-to-end/cases/expected/query/force-focus_focus-1-result.html
  test/end-to-end/cases/expected/query/force-focus_focus-1-result.xml
  test/end-to-end/cases/expected/stylesheet/force-focus_escape-for-regex-junit.xml
  test/end-to-end/cases/expected/stylesheet/force-focus_escape-for-regex-result.html
  test/end-to-end/cases/expected/stylesheet/force-focus_escape-for-regex-result.xml
  test/end-to-end/cases/expected/stylesheet/force-focus_focus-1-junit.xml
  test/end-to-end/cases/expected/stylesheet/force-focus_focus-1-result.html
  test/end-to-end/cases/expected/stylesheet/force-focus_focus-1-result.xml
  test/end-to-end/cases/force-focus-reporter.xsl
  test/end-to-end/cases/force-focus_escape-for-regex.xspec
  test/end-to-end/cases/force-focus_focus-1.xspec
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#1133 fix(report): undeclare default namespace when reporting results in XML
  src/common/parse-report.xsl
  src/compiler/generate-query-utils.xqm
  src/compiler/generate-tests-utils.xsl
  src/reporter/format-xspec-report.xsl
  test/ant/worker/generate.xsl
  test/end-to-end/cases/expected/query/ambiguous-expect-result.xml
  test/end-to-end/cases/expected/query/issue-151-result.xml
  test/end-to-end/cases/expected/query/issue-177-result.xml
  test/end-to-end/cases/expected/query/issue-346-result.xml
  test/end-to-end/cases/expected/query/issue-355-result.xml
  test/end-to-end/cases/expected/query/issue-450-451-result.xml
  test/end-to-end/cases/expected/query/issue-452-result.xml
  test/end-to-end/cases/expected/query/issue-467-result.xml
  test/end-to-end/cases/expected/query/issue-67-result.xml
  test/end-to-end/cases/expected/query/report-result.xml
  test/end-to-end/cases/expected/query/serialize-result.xml
  test/end-to-end/cases/expected/query/three-dots-result.xml
  test/end-to-end/cases/expected/schematron/issue-693-result.html
  test/end-to-end/cases/expected/schematron/issue-693-result.xml
  test/end-to-end/cases/expected/schematron/schematron-023-result.html
  test/end-to-end/cases/expected/schematron/schematron-023-result.xml
  test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.html
  test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.xml
  test/end-to-end/cases/expected/schematron/tvt_label_schematron-result.xml
  test/end-to-end/cases/expected/stylesheet/ambiguous-expect-result.xml
  test/end-to-end/cases/expected/stylesheet/coverage-tutorial-result.xml
  test/end-to-end/cases/expected/stylesheet/custom-coverage-report-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-151-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-177-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-214-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-23_2-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-346-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-355-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-450-451-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-450-451_stylesheet-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-452-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-467-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-67-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-778_ws-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-793-cr-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-793-crlf-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-793-lf-result.xml
  test/end-to-end/cases/expected/stylesheet/mode-all-result.xml
  test/end-to-end/cases/expected/stylesheet/report-result.xml
  test/end-to-end/cases/expected/stylesheet/result-naming-collision-result.xml
  test/end-to-end/cases/expected/stylesheet/rule-result.xml
  test/end-to-end/cases/expected/stylesheet/serialize-result.xml
  test/end-to-end/cases/expected/stylesheet/three-dots-result.xml
  test/end-to-end/cases/expected/stylesheet/xslt2-result.xml
  test/end-to-end/cases/issue-693.xspec
  test/end-to-end/cases/schematron-023.xspec
  test/end-to-end/cases/schematron-import_demo-02-PhaseB.xspec
  test/end-to-end/cases/tvt_label_schematron.xspec
  test/end-to-end/processor/xml/_normalizer.xsl
  test/generate-query-utils.xspec
  test/generate-tests-utils.xspec
Labels: bug

#1128 feat: compiler Saxon configuration in Ant build
  build.xml
  test/compiler-saxon-config/config.xml
  test/compiler-saxon-config/test.xspec
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#1091 refactor(report): remove recursive call from coverage-report.xsl
  src/reporter/coverage-report.xsl
  test/ant/worker/generate.xsl
  test/issue-215.xspec
Labels: enhancement

#1136 fix(report): resolve coverage stylesheet URI via xml:base
  src/reporter/coverage-report.xsl
  test/issue-1135.xspec
  test/issue-1135/issue-1135.xsl
Labels: bug

#1103 feat: x:helper
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  src/schemas/xspec.rnc
  src/schematron/schut-to-xspec.xsl
  test/external_helper.xspec
  test/global-override.xspec
  test/global.xsl
  test/helper.sch
  test/helper.xspec
  test/helper/imported.xspec
  test/helper/override.xsl
  test/helper_override.xspec
  test/helper_schematron.xspec
  test/helper_tutorial_ws-only-text.xspec
  test/helper_xslt-package.xspec
  test/square.xsl
  test/ws-only-text.xsl
  test/ws-only-text_stylesheet.xspec
  tutorial/helper/ws-only-text/context.xml
  tutorial/helper/ws-only-text/expect.xml
  tutorial/helper/ws-only-text/href.xspec
  tutorial/helper/ws-only-text/test-helper.xsl
  tutorial/helper/ws-only-text/test-target.xsl
Labels: enhancement

#1138 build(oxygen): add-on v2.0.3
  editors/oxygen/add-on/description/latest.xhtml
  oxygen-addon.xml
  xspec.xpr
Labels: release

#1139 refactor: extract gatherer.xsl from generate-common-tests.xsl
  src/compiler/gatherer.xsl
  src/compiler/generate-common-tests.xsl
Labels: enhancement

#1140 refactor(schematron): group default mode templates
  src/schematron/schut-to-xspec.xsl
Labels: enhancement

#1141 feat: support XML 1.1 in Ant build
  build.xml
  src/harnesses/basex/basex-server-xquery-harness.xproc
  src/harnesses/basex/basex-standalone-xquery-harness.xproc
  src/harnesses/exist/exist-xquery-harness.xproc
  src/harnesses/marklogic/ml-xquery-harness.xproc
  src/harnesses/saxon/saxon-xquery-harness.xproc
  src/harnesses/saxon/saxon-xslt-harness.xproc
  test/ant/worker/build-worker_util.xml
  test/ant/worker/generate.xsl
  test/end-to-end/cases/expected/query/xml-1-1-junit.xml
  test/end-to-end/cases/expected/query/xml-1-1-result.html
  test/end-to-end/cases/expected/query/xml-1-1-result.xml
  test/end-to-end/cases/expected/schematron/xml-1-1_schematron-junit.xml
  test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.html
  test/end-to-end/cases/expected/schematron/xml-1-1_schematron-result.xml
  test/end-to-end/cases/expected/stylesheet/xml-1-1-junit.xml
  test/end-to-end/cases/expected/stylesheet/xml-1-1-result.html
  test/end-to-end/cases/expected/stylesheet/xml-1-1-result.xml
  test/end-to-end/cases/xml-1-1.sch
  test/end-to-end/cases/xml-1-1.xspec
  test/end-to-end/cases/xml-1-1_0007.xml
  test/end-to-end/cases/xml-1-1_config_compiler.xml
  test/end-to-end/cases/xml-1-1_config_runtime.xml
  test/end-to-end/cases/xml-1-1_schematron.xspec
  test/end-to-end/processor/base/_deserializer.xsl
  test/end-to-end/processor/base/compare.xsl
  test/end-to-end/processor/base/normalize.xsl
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#1107 feat(schematron): compare location based on node identity
  misc/archive/src/schematron/sch-location-compare.xsl
  misc/archive/test/sch-location-compare.xspec
  src/compiler/generate-xspec-tests.xsl
  src/schematron/generate-node-selector.xsl
  src/schematron/schut-to-xspec.xsl
  src/schematron/select-node.xsl
  test/ant/worker/build-worker_util.xml
  test/ant/worker/generate.xsl
  test/generate-node-selector.xspec
  test/issue-396_schxslt.xspec
  test/schematron/schut-to-xspec-012-out.xspec
  test/schxslt/compile-for-svrl.xsl
  test/schxslt/expand.xsl
  test/schxslt/include.xsl
  test/select-node.xspec
  xspec.xpr
Labels: enhancement

#1142 refactor(xslt): ignore all src files in coverage trace
  bin/xspec.bat
  bin/xspec.sh
  build.xml
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.class
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.java
Labels: enhancement

#1143 refactor: discard x:import in x:gather-specs mode
  src/compiler/gatherer.xsl
  src/compiler/generate-common-tests.xsl
Labels: enhancement

#1144 fix(schematron): fix importing global parameters for Step 3
  src/schematron/generate-step3-wrapper.xsl
  test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-junit.xml
  test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.html
  test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.xml
  test/end-to-end/cases/schematron-import_demo-02-PhaseB.xspec
Labels: bug

#1145 fix(schematron): resolve x:import properly in schut-to-xspec.xsl
  src/compiler/gatherer.xsl
  src/schematron/schut-to-xspec.xsl
  test/avt_schematron.xspec
  test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-junit.xml
  test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.html
  test/end-to-end/cases/expected/schematron/schematron-import_demo-02-PhaseB-result.xml
  test/end-to-end/cases/label-element.xspec
  test/issue-396.xspec
  test/issue-396_schxslt.xspec
  test/issue-547.xspec
  test/schematron-014.xspec
  test/schematron-015.xspec
  test/schematron-016.xspec
  test/schematron-017.xspec
  test/schematron-018.xspec
  test/schematron-020.xspec
  test/schematron-021.xspec
  test/schematron-022.xspec
  test/schematron-024.xspec
  test/schematron/schematron-param-001-step3.xsl
  test/schematron/schematron-param-001.xspec
  test/schematron/schut-to-xspec-001-out.xspec
  test/schematron/schut-to-xspec-002-out.xspec
  test/schematron/schut-to-xspec-003-out.xspec
  test/schematron/schut-to-xspec-004-out.xspec
  test/schematron/schut-to-xspec-005-out.xspec
  test/schematron/schut-to-xspec-006-out.xspec
  test/schematron/schut-to-xspec-007-out.xspec
  test/schematron/schut-to-xspec-008-out.xspec
  test/schematron/schut-to-xspec-009-out.xspec
  test/schematron/schut-to-xspec-010-out.xspec
  test/schematron/schut-to-xspec-011-out.xspec
  test/schematron/schut-to-xspec-012-out.xspec
  test/schematron/schut-to-xspec-013-out.xspec
  test/schematron/schut-to-xspec-014-in.xspec
  test/schematron/schut-to-xspec-014-out.xspec
  test/schut-to-xspec.xspec
  test/schut-to-xspec_helper.xsl
  test/tvt_schematron.xspec
  test/win-bats/collection.xml
  test/xspec.bats
Labels: bug

#1150 test: print unparsed result on end-to-end test failure
  test/end-to-end/processor/base/compare.xsl
Labels: test

#1157 test(schematron): skip xml-1-1_schematron.xspec on Travis CI
  test/ant/worker/generate.xsl
  test/end-to-end/cases/xml-1-1_schematron.xspec
Labels: test

#1149 refactor: split src/compiler/generate-*-utils.*
  src/common/deep-equal.xqm
  src/common/deep-equal.xsl
  src/common/parse-report.xsl
  src/common/report-sequence.xqm
  src/common/report-sequence.xsl
  src/common/saxon-config.xsl
  src/common/wrap.xsl
  src/common/xml-report-serialization-parameters.xml
  src/common/xml-report-serialization-parameters.xsl
  src/common/xspec-utils.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-query-utils.xqm
  src/compiler/generate-xspec-tests.xsl
  src/harnesses/basex/basex-standalone-xquery-harness.xproc
  src/harnesses/harness-lib.xpl
  src/harnesses/saxon/saxon-xquery-harness.xproc
  src/reporter/coverage-report.xsl
  src/reporter/format-utils.xsl
  src/reporter/format-xspec-report.xsl
  src/schematron/schut-to-xspec.xsl
  test/deep-equal.xspec
  test/generate-tests-utils.xspec
  test/generate-x-utils.xspec
  test/issue-47.xspec
  test/issue-59_stylesheet.xspec
  test/report-sequence.xsl
  test/report-sequence.xspec
  test/report-sequence_query.xspec
  test/report-sequence_query_schema-aware.xspec
  test/report-sequence_stylesheet.xspec
  test/report-sequence_stylesheet_schema-aware.xspec
  test/schema/build.xml
  test/wrap.xspec
  test/xspec-utils.xspec
  test/xspec-utils_stylesheet.xspec
  tutorial/under-the-hood/Compilation.md
  xspec.xpr
Labels: enhancement

#1120 feat(xslt): static parameters
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-helper.xsl
  src/compiler/generate-tests-helper.xsl
  src/compiler/generate-xspec-tests.xsl
  src/schemas/xspec.rnc
  src/schematron/generate-step3-wrapper.xsl
  test/external_xslt-package_arith_private.xspec
  test/static-param/disallowed_query.xspec
  test/static-param/disallowed_schematron.xspec
  test/static-param/disallowed_stylesheet.xspec
  test/win-bats/collection.xml
  test/xslt-package/arith/package/complex-arithmetic_private.xsl
  test/xspec.bats
Labels: enhancement

#1153 ci: print the number of logical processors on *nix
  test/ci/print-env.sh
Labels: test

#1160 build(oxygen): add-on v2.0.4
  editors/oxygen/add-on/description/latest.xhtml
  oxygen-addon.xml
  xspec.xpr
Labels: release

#1161 test: rename generate-x-utils/ to deep-equal/
  test/deep-equal.xspec
  test/deep-equal/09.xml
  test/deep-equal/20.xml
  test/deep-equal/ws-09.xml
  test/deep-equal/ws-20.xml
Labels: test

#1158 fix(report): serialize text node report
  src/reporter/format-utils.xsl
  test/end-to-end/cases/expected/query/serialize-junit.xml
  test/end-to-end/cases/expected/query/serialize-result.html
  test/end-to-end/cases/expected/query/serialize-result.xml
  test/end-to-end/cases/expected/query/xml-1-1-result.html
  test/end-to-end/cases/expected/stylesheet/serialize-junit.xml
  test/end-to-end/cases/expected/stylesheet/serialize-result.html
  test/end-to-end/cases/expected/stylesheet/serialize-result.xml
  test/end-to-end/cases/expected/stylesheet/xml-1-1-result.html
  test/end-to-end/cases/serialize.xspec
Labels: bug

#1166 test: rename x-setup-context.xspec to context-param.xspec
  test/context-param.xml
  test/context-param.xspec
  test/node-selection_stylesheet.xspec
Labels: test

#1167 refactor: x:resolve-import()
  src/compiler/gatherer.xsl
  src/compiler/generate-common-tests.xsl
  src/schematron/generate-step3-wrapper.xsl
  src/schematron/schut-to-xspec.xsl
Labels: enhancement

#1168 refactor: load util modules using xsl:for-each
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  tutorial/under-the-hood/Compilation.md
Labels: enhancement

#1162 refactor: rename compiler master files
  bin/xspec.bat
  bin/xspec.sh
  build.xml
  src/compiler/compile-xquery-tests.xsl
  src/compiler/compile-xslt-tests.xsl
  src/compiler/generate-common-tests.xsl
  src/harnesses/harness-lib.xpl
  test/compile-xslt-tests.xspec
  test/compile-xslt-tests/expect.xspec
  test/compile-xslt-tests/scenario.xspec
  test/end-to-end/processor/xml/_serializer.xsl
  test/override-id/compile-xquery-tests.xsl
  test/override-id/compile-xslt-tests.xsl
  test/schema/build.xml
  test/win-bats/collection.xml
  test/xspec.bats
  xspec.xpr
Labels: enhancement

#1171 refactor: replace xsl:perform-sort with fn:sort()
  src/common/xspec-utils.xsl
  test/end-to-end/processor/base/compare.xsl
  test/xspec-name.xspec
Labels: enhancement

#1180 refactor: extract test utils from xspec-utils.xsl
  src/common/xspec-utils.xsl
  test/ant/worker/generate.xsl
  test/end-to-end/processor/base/compare.xsl
  test/end-to-end/processor/base/normalize.xsl
  test/test-utils.xsl
  test/test-utils.xspec
  test/xspec-utils_stylesheet.xspec
Labels: enhancement

#1181 refactor: extract x:locate-schematron-uri() from xspec-utils.xsl
  src/common/xspec-utils.xsl
  src/schematron/generate-step3-wrapper.xsl
  src/schematron/locate-schematron-uri.xsl
  src/schematron/schut-to-xslt.xsl
  test/locate-schematron-uri.xspec
  test/xspec-utils_stylesheet.xspec
Labels: enhancement

#1186 test: rename test/eqname*.* to use-uqname*.*
  test/eqname.xqm
  test/eqname.xsl
  test/no-prefix_stylesheet.xspec
  test/use-uqname.xqm
  test/use-uqname.xsl
  test/use-uqname.xspec
  test/use-uqname_stylesheet.xspec
  test/variable/reserved-lexical-qname-in-global.xspec
  test/variable/reserved-uqname-in-local.xspec
  test/win-bats/collection.xml
  test/xspec.bats
Labels: test

#1189 refactor: extract 'trim' functions from xspec-utils.xsl
  src/common/trim.xsl
  src/common/xspec-utils.xsl
  src/compiler/generate-common-tests.xsl
  src/reporter/format-xspec-report.xsl
  src/schematron/generate-step3-wrapper.xsl
  src/schematron/schut-to-xslt.xsl
  src/schematron/schut-to-xspec.xsl
  test/ant/worker/generate.xsl
  test/trim.xspec
  test/xspec-utils_stylesheet.xspec
Labels: enhancement

#1193 test(maven): test loading src stylesheet files from jar
  test/ci/build_test-maven-jar.xml
  test/ci/test-maven-jar.cmd
  test/ci/test-maven-jar.sh
  test/ci/test-maven-jar/compile-xslt-tests.xsl
  test/ci/test-maven-jar/coverage-report.xsl
  test/ci/test-maven-jar/format-xspec-report.xsl
  test/ci/test-maven-jar/junit-report.xsl
Labels: test

#1197 build(maven): retry dependency download
  .mvn/maven.config
Labels: enhancement

#1201 ci: retry downloading deps in build_install-deps.xml
  test/ci/build_install-deps.xml
Labels: test

#1200 docs(xproc): update utils-lib comments
  src/harnesses/basex/basex-server-xquery-harness.xproc
  src/harnesses/exist/exist-xquery-harness.xproc
  src/harnesses/marklogic/ml-xquery-harness.xproc
Labels: documentation

#1202 perf(xslt): disable cache only when $x:saxon-config is not empty
  src/compiler/compile-xslt-tests.xsl
Labels: enhancement

#1206 ci(deps): bump Saxon from 10.1 to 10.2
  test/ant/worker/generate.xsl
  test/avt_schematron.xspec
  test/ci/env/saxon-10.env
  test/end-to-end/cases/issue-693.xspec
  test/end-to-end/cases/label-element.xspec
  test/end-to-end/cases/schematron-023.xspec
  test/end-to-end/cases/schematron-import_demo-02-PhaseB.xspec
  test/end-to-end/cases/tvt_label_schematron.xspec
  test/end-to-end/cases/xml-1-1_schematron.xspec
  test/issue-396.xspec
  test/issue-396_schxslt.xspec
  test/issue-547.xspec
  test/run-bats.cmd
  test/run-bats.sh
  test/schematron-016.xspec
  test/schematron-017.xspec
  test/schematron-018.xspec
  test/schematron-020.xspec
  test/schematron-021.xspec
  test/schematron-022.xspec
  test/schematron-024.xspec
  test/tvt_schematron.xspec
  test/win-bats/collection.xml
  test/xspec.bats
Labels: test

#1192 refactor: rename confusing 'call' templates
  src/compiler/compile-xquery-tests.xsl
  src/compiler/compile-xslt-tests.xsl
  src/compiler/generate-common-tests.xsl
  tutorial/under-the-hood/Compilation.md
Labels: enhancement
