Repository xspec/xspec, pull requests merged in 2020-02, with the labels that each got.

#740 refactor(oxygen): update Oxygen XProc transformation scenarios
  xspec.framework
Labels: enhancement

#768 fix(schematron): fix xspec.bat handling Schematron path with space
  bin/xspec.bat
  test/win-bats/collection.xml
Labels: bug

#731 fix(xslt): fix xslt-version inheritance
  src/common/xspec-utils.xsl
  test/end-to-end/cases/expected/stylesheet/xspec-xslt2-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-xslt2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-xslt2-result.xml
  test/xspec-utils_stylesheet.xspec
  test/xspec-xslt1.xspec
Labels: bug

#767 fix(xproc): indent results in HTML report
  CONTRIBUTING.md
  src/harnesses/harness-lib.xpl
  test/end-to-end/processor/html/_normalizer.xsl
  test/win-bats/collection.xml
  test/win-bats/stub.cmd
  test/xspec-72.xspec
  test/xspec.bats
Labels: bug

#734 feat(report): overridable ID generation
  build.xml
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  test/generate-xspec-tests.xspec
  test/override-id/generate-xspec-tests.xsl
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#769 ci(deps): bump BaseX from 8.6.4 to 9.3.1
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
Labels: test

#741 refactor(oxygen): add Oxygen XSLT master files settings
  xspec.xpr
Labels: enhancement

#631 feat: also accept 'schematron', 'xquery', or 'xslt' for Ant 'test.type'
  build.xml
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#776 ci: skip codespell .git dir
  test/ci/run-codespell.cmd
  test/ci/run-codespell.sh
Labels: test

#775 ci: suppress codespell warnings about fixes disabled in dictionary
  test/ci/run-codespell.cmd
  test/ci/run-codespell.sh
Labels: test

#774 test: fix typo 'poisition'
  test/xspec-param-position.xspec
Labels: bug, test

#771 docs: mention Schematron in README.md
  README.md
Labels: documentation

#773 feat(xslt): report additional types
  src/compiler/generate-query-utils.xql
  src/compiler/generate-tests-utils.xsl
  test/end-to-end/cases/expected/query/xspec-report_schema-aware-junit.xml
  test/end-to-end/cases/expected/query/xspec-report_schema-aware-result.html
  test/end-to-end/cases/expected/query/xspec-report_schema-aware-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-report_schema-aware-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-report_schema-aware-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report_schema-aware-result.xml
  test/end-to-end/cases/xspec-report_schema-aware.xspec
  test/generate-query-utils_schema-aware.xspec
  test/generate-tests-utils_schema-aware.xspec
Labels: enhancement

#779 ci(deps): bump Oxygen lib versions
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
  test/ci/azure-pipelines_windows.yml
Labels: test

#781 build(oxygen): add-on v0.0.5
  editors/oxygen/add-on/description/latest.xhtml
  oxygen-addon.xml
Labels: release

#783 docs: add PlantUML diagram to test/ant/README.md
  test/ant/README.md
  test/ant/diagram.txt
Labels: documentation, test

#784 test: update expected result of schema-aware end-to-end test
  test/end-to-end/cases/expected/query/xspec-report_schema-aware-result.html
  test/end-to-end/cases/expected/query/xspec-report_schema-aware-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-report_schema-aware-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report_schema-aware-result.xml
Labels: test

#785 test(xslt): skip testing additional type report on Saxon 9.7
  test/ant/worker/generate.xsl
  test/end-to-end/cases/xspec-report_schema-aware.xspec
  test/generate-tests-utils_schema-aware.xspec
Labels: test

#790 test: fix nonexistent call rmdir-if-exists
  test/win-bats/collection.xml
Labels: test

#782 refactor: test:generate-variable-declarations mode
  src/compiler/generate-common-tests.xsl
  src/compiler/generate-query-helper.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-tests-helper.xsl
  src/compiler/generate-xspec-tests.xsl
  src/schematron/generate-step3-wrapper.xsl
Labels: enhancement

#794 fix(report): fix tokenizing stylesheet CR lines on code coverage
  src/reporter/coverage-report.xsl
  test/end-to-end/cases/.gitattributes
  test/end-to-end/cases/expected/stylesheet/xspec-793-cr-coverage.html
  test/end-to-end/cases/expected/stylesheet/xspec-793-cr-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-793-cr-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-793-cr-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-793-crlf-coverage.html
  test/end-to-end/cases/expected/stylesheet/xspec-793-crlf-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-793-crlf-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-793-crlf-result.xml
  test/end-to-end/cases/expected/stylesheet/xspec-793-lf-coverage.html
  test/end-to-end/cases/expected/stylesheet/xspec-793-lf-junit.xml
  test/end-to-end/cases/expected/stylesheet/xspec-793-lf-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-793-lf-result.xml
  test/end-to-end/cases/xspec-793-cr.xsl
  test/end-to-end/cases/xspec-793-cr.xspec
  test/end-to-end/cases/xspec-793-crlf.xsl
  test/end-to-end/cases/xspec-793-crlf.xspec
  test/end-to-end/cases/xspec-793-lf.xsl
  test/end-to-end/cases/xspec-793-lf.xspec
Labels: bug

#795 feat(xslt): code coverage on Saxon-HE
  bin/xspec.bat
  bin/xspec.sh
  build.xml
  java/io/xspec/xspec/saxon/funcdefs/LineNumber$1.class
  java/io/xspec/xspec/saxon/funcdefs/LineNumber.class
  java/io/xspec/xspec/saxon/funcdefs/LineNumber.java
  src/reporter/coverage-report-config.xml
  src/reporter/coverage-report.xsl
  test/ant/build.xml
  test/ant/worker/build-worker_util.xml
  test/ant/worker/generate.xsl
  test/line-number/common.xspec
  test/line-number/disabled-config.xml
  test/line-number/doc.xml
  test/line-number_disabled.xspec
  test/line-number_enabled.xspec
  test/run-bats.cmd
  test/run-bats.sh
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#742 feat(schema): add Schematron schema for XSpec
  CONTRIBUTING.md
  src/schemas/xspec.sch
  test/end-to-end/cases/schematron-023.xspec
  test/xspec-sch.xspec
  test/xspec-space.xspec
  test/xspec-space_stylesheet.xspec
  xspec.framework
Labels: enhancement

#798 refactor: remove redundant xsl:element/attribute(namespace)
  src/compiler/generate-common-tests.xsl
Labels: enhancement

#800 build(oxygen): add-on v0.0.6
  editors/oxygen/add-on/description/latest.xhtml
  oxygen-addon.xml
Labels: release
