Repository xspec/xspec, pull requests merged in 2020-09, with the labels that each got.

#1221 refactor(xslt): remove duplicate xsl:namespace-alias
  src/compiler/compile-xslt-tests.xsl
  src/compiler/xslt/compile/compile-expect.xsl
  src/compiler/xslt/compile/compile-scenario.xsl
Labels: enhancement

#1224 test(schematron): skip xml-1-1_schematron.xspec on GitHub Actions macOS
  test/ant/worker/generate.xsl
Labels: test

#1226 fix: resolve relative `jar:` scheme in coverage trace listener
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.class
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.java
  test/ci/build_test-maven-jar.xml
  test/ci/test-maven-jar.cmd
  test/ci/test-maven-jar.sh
  test/ci/test-maven-jar/compile-xslt-tests.xsl
  test/ci/test-maven-jar/coverage-report.xsl
  test/ci/test-maven-jar/format-xspec-report.xsl
  test/ci/test-maven-jar/junit-report.xsl
Labels: bug

#1222 fix(xquery): fix issue 446 (x:pending may crash on XQuery)
  src/compiler/base/invoke-compiled/invoke-compiled-child-scenarios-or-expects.xsl
  src/compiler/xquery/compile/compile-scenario.xsl
  src/compiler/xquery/invoke-compiled/invoke-compiled-current-scenario-or-expect.xsl
  src/compiler/xslt/invoke-compiled/invoke-compiled-current-scenario-or-expect.xsl
  test/end-to-end/cases/expected/query/issue-446_1-junit.xml
  test/end-to-end/cases/expected/query/issue-446_1-result.html
  test/end-to-end/cases/expected/query/issue-446_1-result.xml
  test/end-to-end/cases/expected/query/issue-446_2-junit.xml
  test/end-to-end/cases/expected/query/issue-446_2-result.html
  test/end-to-end/cases/expected/query/issue-446_2-result.xml
  test/end-to-end/cases/expected/query/issue-446_3-junit.xml
  test/end-to-end/cases/expected/query/issue-446_3-result.html
  test/end-to-end/cases/expected/query/issue-446_3-result.xml
  test/end-to-end/cases/expected/query/issue-446_4-junit.xml
  test/end-to-end/cases/expected/query/issue-446_4-result.html
  test/end-to-end/cases/expected/query/issue-446_4-result.xml
  test/end-to-end/cases/expected/query/issue-446_5-junit.xml
  test/end-to-end/cases/expected/query/issue-446_5-result.html
  test/end-to-end/cases/expected/query/issue-446_5-result.xml
  test/end-to-end/cases/expected/query/issue-528-junit.xml
  test/end-to-end/cases/expected/query/issue-528-result.html
  test/end-to-end/cases/expected/query/issue-528-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-446_1-junit.xml
  test/end-to-end/cases/expected/stylesheet/issue-446_1-result.html
  test/end-to-end/cases/expected/stylesheet/issue-446_1-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-446_2-junit.xml
  test/end-to-end/cases/expected/stylesheet/issue-446_2-result.html
  test/end-to-end/cases/expected/stylesheet/issue-446_2-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-446_3-junit.xml
  test/end-to-end/cases/expected/stylesheet/issue-446_3-result.html
  test/end-to-end/cases/expected/stylesheet/issue-446_3-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-446_4-junit.xml
  test/end-to-end/cases/expected/stylesheet/issue-446_4-result.html
  test/end-to-end/cases/expected/stylesheet/issue-446_4-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-446_5-junit.xml
  test/end-to-end/cases/expected/stylesheet/issue-446_5-result.html
  test/end-to-end/cases/expected/stylesheet/issue-446_5-result.xml
  test/end-to-end/cases/issue-446_1.xspec
  test/end-to-end/cases/issue-446_2.xspec
  test/end-to-end/cases/issue-446_3.xspec
  test/end-to-end/cases/issue-446_4.xspec
  test/end-to-end/cases/issue-446_5.xspec
  test/end-to-end/cases/issue-528.xspec
  test/variable.xspec
  tutorial/under-the-hood/Compilation.md
Labels: bug

#1225 refactor: replace $stacked-variables with accumulator
  src/compiler/base/compile/compile-child-scenarios-or-expects.xsl
  src/compiler/base/invoke-compiled/invoke-compiled-child-scenarios-or-expects.xsl
  src/compiler/base/main.xsl
  src/compiler/xquery/compile/compile-scenario.xsl
  src/compiler/xslt/compile/compile-scenario.xsl
  src/compiler/xslt/invoke-compiled/invoke-compiled-current-scenario-or-expect.xsl
Labels: enhancement

#1229 build(oxygen): add-on v2.0.5
  editors/oxygen/add-on/description/latest.xhtml
  oxygen-addon.xml
  xspec.xpr
Labels: release

#1230 test(schematron): test with SchXslt v1.4.7
  test/schxslt/base-uri.xsl
  test/schxslt/compile-for-svrl.xsl
  test/schxslt/expand.xsl
  test/schxslt/include.xsl
Labels: test

#1227 fix(xslt): fix issue 746 (transform() crashes Code Coverage)
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.class
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.java
  test/issue-746.xsl
  test/issue-746.xspec
Labels: bug

#1235 ci(deps): bump BaseX from 9.4.1 to 9.4.3
  test/ci/env/global.env
  test/ci/print-env.sh
Labels: test

#1236 test: harden risky attribute(test)
  test/select-node.xspec
  test/x-context.xspec
Labels: test

#1234 refactor(xslt): suppress meaningless map-entry for $transform-options
  src/compiler/xslt/external/transform-options.xsl
Labels: enhancement

#1231 test(xslt): more tests for run-as=external
  test/ant/worker/generate.xsl
  test/end-to-end/cases/expected/stylesheet/external_coverage-tutorial-coverage.html
  test/end-to-end/cases/expected/stylesheet/external_coverage-tutorial-junit.xml
  test/end-to-end/cases/expected/stylesheet/external_coverage-tutorial-result.html
  test/end-to-end/cases/expected/stylesheet/external_coverage-tutorial-result.xml
  test/end-to-end/cases/expected/stylesheet/external_function-junit.xml
  test/end-to-end/cases/expected/stylesheet/external_function-result.html
  test/end-to-end/cases/expected/stylesheet/external_function-result.xml
  test/end-to-end/cases/expected/stylesheet/external_global-override-junit.xml
  test/end-to-end/cases/expected/stylesheet/external_global-override-result.html
  test/end-to-end/cases/expected/stylesheet/external_global-override-result.xml
  test/end-to-end/cases/expected/stylesheet/external_import-junit.xml
  test/end-to-end/cases/expected/stylesheet/external_import-result.html
  test/end-to-end/cases/expected/stylesheet/external_import-result.xml
  test/end-to-end/cases/expected/stylesheet/external_issue-450-451-junit.xml
  test/end-to-end/cases/expected/stylesheet/external_issue-450-451-result.html
  test/end-to-end/cases/expected/stylesheet/external_issue-450-451-result.xml
  test/end-to-end/cases/expected/stylesheet/external_issue-450-451_stylesheet-junit.xml
  test/end-to-end/cases/expected/stylesheet/external_issue-450-451_stylesheet-result.html
  test/end-to-end/cases/expected/stylesheet/external_issue-450-451_stylesheet-result.xml
  test/end-to-end/cases/expected/stylesheet/global-override-junit.xml
  test/end-to-end/cases/expected/stylesheet/global-override-result.html
  test/end-to-end/cases/expected/stylesheet/global-override-result.xml
  test/end-to-end/cases/external_coverage-tutorial.xspec
  test/end-to-end/cases/external_function.xspec
  test/end-to-end/cases/external_global-override.xspec
  test/end-to-end/cases/external_import.xspec
  test/end-to-end/cases/external_issue-450-451.xspec
  test/end-to-end/cases/external_issue-450-451_stylesheet.xspec
  test/end-to-end/cases/global-override.xsl
  test/end-to-end/cases/global-override.xspec
  test/external_catch_stylesheet.xspec
  test/external_context-param.xspec
  test/external_global-context.xsl
  test/external_global-context.xspec
  test/external_mirror.xsl
  test/external_multiple-context-items.xspec
  test/external_multiple-context-nodes.xspec
  test/external_multiple-context-values.xspec
  test/external_no-prefix_stylesheet.xspec
  test/external_param-as.xspec
  test/external_param-as_stylesheet.xspec
  test/external_template-context.xspec
  test/external_tunnel-param.xspec
  test/external_use-uqname_stylesheet.xspec
  test/external_xmlns.xsl
  test/external_xmlns.xspec
  test/global-override.xspec
  test/global.xsl
  test/template-context.xspec
Labels: test

#1228 refactor: compile without sibling walk
  src/compiler/base/compile/compile-child-scenarios-or-expects.xsl
  src/compiler/base/invoke-compiled/invoke-compiled-child-scenarios-or-expects.xsl
  src/compiler/base/util/compiler-misc-utils.xsl
  src/compiler/xquery/compile/compile-scenario.xsl
  src/compiler/xslt/compile/compile-scenario.xsl
Labels: enhancement

#1241 perf: assume x:scenario and x:expect won't be in user-content
  src/compiler/base/combine/mode/assign-id.xsl
  src/compiler/base/combine/mode/generate-id.xsl
  src/compiler/base/combine/mode/unshare-scenarios.xsl
Labels: enhancement

#1240 test(report): valid report-sequence_(query|stylesheet).xspec
  test/report-sequence/attributes-and-content.xml
  test/report-sequence/attributes.xml
  test/report-sequence/empty-sequence.xml
  test/report-sequence/integer.xml
  test/report-sequence/qname.xml
  test/report-sequence/string.xml
  test/report-sequence/uri.xml
  test/report-sequence_query.xspec
  test/report-sequence_stylesheet.xspec
  test/schema/build.xml
Labels: test

#1237 docs(xslt): update Compilation.md for run-as=external
  src/compiler/xslt/external/transform-options.xsl
  src/compiler/xslt/main.xsl
  test/external_under-the-hood_compilation-sut_template.xspec
  tutorial/under-the-hood/Compilation.md
  tutorial/under-the-hood/compilation-sut_template.xspec
  tutorial/under-the-hood/compilation-sut_template_external.xspec
Labels: documentation

#1242 ci(maven): error when no files found in upload-artifact action
  .github/workflows/test.yml
Labels: test

#1244 test(schematron): test with SchXslt v1.5
  test/schxslt/base-uri.xsl
Labels: test

#1248 ci(deps): bump XML Calabash from 1.2.1 to 1.2.3
  test/ci/env/saxon-9-9.env
Labels: test

#1247 docs(schema): x:context can accept non-node items
  src/schemas/xspec.rnc
  test/external_non-node-context.xspec
  test/non-node-context.xspec
Labels: enhancement

#1251 test(schematron): test with SchXslt v1.5.1
  test/schxslt/base-uri.xsl
Labels: test

#1246 fix(xslt): variables declared between x:context and x:call
  src/compiler/xslt/compile/compile-scenario.xsl
  test/variable_stylesheet.xspec
Labels: bug

#1250 refactor(xproc): exclude inline prefixes from temp XQuery compiler
  src/harnesses/harness-lib.xpl
Labels: enhancement

#1252 ci(deps): bump XML Calabash from 1.2.3 to 1.2.4
  test/ci/env/saxon-10.env
  test/ci/env/saxon-9-9.env
  test/win-bats/collection.xml
  test/xspec.bats
Labels: test
