Repository xspec/xspec, pull requests merged in 2020-05, with the labels that each got.

#933 docs: update "Compilation" doc
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-xspec-tests.xsl
  tutorial/under-the-hood/Compilation.md
  tutorial/under-the-hood/compilation-simple-suite.xquery
  tutorial/under-the-hood/compilation-simple-suite.xsl
  tutorial/under-the-hood/compilation-simple-suite.xspec
  tutorial/under-the-hood/compilation-sut.xquery
  tutorial/under-the-hood/compilation-sut.xsl
  tutorial/under-the-hood/compilation-sut_query.xspec
  tutorial/under-the-hood/compilation-sut_stylesheet.xspec
Labels: documentation

#945 test: refactor expressions in test/**/*.xsl with XPath 3
  test/ant/worker/generate.xsl
  test/end-to-end/ant/base/worker/generate.xsl
  test/end-to-end/processor/base/_normalizer.xsl
  test/end-to-end/processor/base/compare.xsl
  test/override-id/generate-xspec-tests.xsl
Labels: test

#941 refactor(xslt): a few more debug prints to XSLTCoverageTraceListener
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.class
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.java
Labels: enhancement

#942 refactor: apostrophe utils
  src/common/xspec-utils.xquery
  src/common/xspec-utils.xsl
  src/compiler/generate-query-tests.xsl
  src/compiler/generate-query-utils.xql
  src/compiler/generate-tests-utils.xsl
  src/compiler/generate-xspec-tests.xsl
  test/win-bats/collection.xml
  test/xspec-utils.xspec
  test/xspec.bats
Labels: enhancement

#943 refactor(schematron): refactor details in schut-to-xspec.xsl
  src/schematron/schut-to-xspec.xsl
  test/end-to-end/cases/expected/schematron/import-demo-02-PhaseB-result.xml
  test/end-to-end/cases/expected/schematron/label-element-result.xml
  test/end-to-end/cases/expected/schematron/schematron-023-result.xml
  test/end-to-end/cases/expected/schematron/xspec-693-result.xml
  test/end-to-end/cases/expected/schematron/xspec-tvt_label_schematron-result.xml
Labels: enhancement

#944 refactor(report): simplify junit-report.xsl
  src/reporter/junit-report.xsl
Labels: enhancement

#946 refactor(report): refactor details in src/reporter/*.xsl
  src/reporter/coverage-report.xsl
  src/reporter/format-utils.xsl
  src/reporter/format-xspec-report-folding.xsl
  src/reporter/format-xspec-report.xsl
  test/end-to-end/processor/coverage/_normalizer.xsl
Labels: enhancement

#949 refactor: details in generate-common-tests.xsl
  src/compiler/generate-common-tests.xsl
Labels: enhancement

#950 refactor: details in xspec-utils.*
  src/common/xspec-utils.xquery
  src/common/xspec-utils.xsl
Labels: enhancement

#951 refactor: details in src/compiler/generate-*-helper.xsl
  src/compiler/generate-query-helper.xsl
  src/compiler/generate-tests-helper.xsl
Labels: enhancement

#954 refactor(xquery): details in generate-query-tests.xsl
  src/compiler/generate-query-tests.xsl
Labels: enhancement

#955 fix(report): plain report hint mark
  src/reporter/format-xspec-report.xsl
  src/reporter/test-report.css
  test/end-to-end/cases/expected/query/label-element-result.html
  test/end-to-end/cases/expected/query/xspec-151-result.html
  test/end-to-end/cases/expected/query/xspec-153-result.html
  test/end-to-end/cases/expected/query/xspec-177-result.html
  test/end-to-end/cases/expected/query/xspec-346-result.html
  test/end-to-end/cases/expected/query/xspec-355-result.html
  test/end-to-end/cases/expected/query/xspec-452-result.html
  test/end-to-end/cases/expected/query/xspec-467-result.html
  test/end-to-end/cases/expected/query/xspec-50-result.html
  test/end-to-end/cases/expected/query/xspec-55-result.html
  test/end-to-end/cases/expected/query/xspec-67-result.html
  test/end-to-end/cases/expected/query/xspec-ambiguous-expect-result.html
  test/end-to-end/cases/expected/query/xspec-focus-1-result.html
  test/end-to-end/cases/expected/query/xspec-function-result.html
  test/end-to-end/cases/expected/query/xspec-import-result.html
  test/end-to-end/cases/expected/query/xspec-imported-result.html
  test/end-to-end/cases/expected/query/xspec-pending-result.html
  test/end-to-end/cases/expected/query/xspec-report-result.html
  test/end-to-end/cases/expected/query/xspec-report_schema-aware-result.html
  test/end-to-end/cases/expected/query/xspec-serialize-result.html
  test/end-to-end/cases/expected/query/xspec-three-dots-result.html
  test/end-to-end/cases/expected/schematron/import-demo-02-PhaseB-result.html
  test/end-to-end/cases/expected/schematron/label-element-result.html
  test/end-to-end/cases/expected/schematron/schematron-023-result.html
  test/end-to-end/cases/expected/schematron/xspec-693-result.html
  test/end-to-end/cases/expected/stylesheet/format-xspec-report-folding-result.html
  test/end-to-end/cases/expected/stylesheet/label-element-result.html
  test/end-to-end/cases/expected/stylesheet/mode-all-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-151-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-153-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-177-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-23_2-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-346-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-355-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-452-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-467-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-50-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-528-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-55-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-67-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-778_ws-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-ambiguous-expect-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-focus-1-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-function-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-import-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-imported-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-pending-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-report_schema-aware-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-result-naming-collision-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-rule-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-serialize-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/xspec-xslt2-result.html
Labels: bug

#956 refactor(xquery): remove verbose fn prefix from generate-query-utils.xql
  src/compiler/generate-query-utils.xql
Labels: enhancement

#957 refactor(xslt): extract deep-equal utils
  src/compiler/generate-query-utils.xql
  src/compiler/generate-tests-utils.xsl
Labels: enhancement

#958 refactor(xquery): extract deep-equal utils
  src/compiler/generate-query-utils.xql
  src/compiler/generate-tests-utils.xsl
Labels: enhancement

#960 ci(deps): bump Saxon from 10.0 to 10.1
  test/ci/env/saxon-10.env
Labels: test

#962 ci: workaround for Azure Pipelines Java 11
  test/ci/print-env.cmd
  test/ci/print-env.sh
  test/ci/switch-java.cmd
Labels: test

#961 refactor(xslt): add attribute(as) to coverage-report.xsl
  src/reporter/coverage-report.xsl
Labels: enhancement

#959 ci(maven): automate Maven deployment
  .github/workflows/maven-deploy.yml
  pom.xml
Labels: release

#964 docs: remove Semantic Pull Requests configuration
  .github/semantic.yml
Labels: documentation

#963 ci(deps): bump Ant from 1.10.7 to 1.10.8
  test/ci/env/global.env
Labels: test

#965 ci(deps): bump BaseX from 9.3.2 to 9.3.3
  test/ci/env/global.env
Labels: test

#970 ci(deps): bump Oxygen Saxon version from 9.9.1.5 to 9.9.1.7
  test/ci/env/oxygen.env
Labels: test

#971 ci: remove Azure Pipelines Java 11 workaround
  test/ci/switch-java.cmd
Labels: test

#934 build(maven): add enduser-files classifier
  assembly/enduser-files.xml
  pom.xml
Labels: enhancement

#973 ci: specify codespell 1.16.0 in requirements-dev.txt
  .dependabot/config.yml
  requirements-dev.txt
  test/ci/run-codespell.cmd
  test/ci/run-codespell.sh
Labels: test

#976 docs: adjust dependabot config
  .commitlintrc.json
  .dependabot/config.yml
  CONTRIBUTING.md
Labels: documentation

#977 ci(deps-dev): run codespell 1.17.0 on Python 3.x
  .github/workflows/lint.yml
  requirements-dev.txt
Labels: test

#974 ci(maven): upload artifact in GitHub Actions test job
  .github/workflows/test.yml
  test/ci/maven-package.cmd
  test/ci/maven-package.sh
  test/ci/print-env.cmd
  test/ci/print-env.sh
Labels: test

#967 fix(maven): include *.java in sources jar and exclude resources
  pom.xml
Labels: bug

#979 build(maven): put resources under unique root
  pom.xml
Labels: enhancement

#913 feat: allow multiple catalog file paths
  build.xml
  test/catalog/01/catalog-public.xml
  test/catalog/01/catalog-rewriteURI.xml
  test/catalog/02/README.md
  test/catalog/02/catalog.xml
  test/catalog/02/importing-stylesheet.xsl
  test/catalog/02/stylesheets/catalog.xml
  test/catalog/02/stylesheets/stylesheet.xsl
  test/catalog/catalog-02.xspec
  test/win-bats/collection.xml
  test/xspec.bats
  xspec.framework
Labels: enhancement

#980 feat: catalog file URIs
  build.xml
  src/ant/generate-catalog.xsl
  test/win-bats/collection.xml
  test/xspec.bats
  xspec.framework
Labels: enhancement

#983 docs(schematron): replace xsl:value-of with xsl:sequence in demo-02.sch
  tutorial/schematron/demo-02.sch
Labels: bug, documentation
