Repository xspec/xspec, pull requests merged in 2023-11, with the labels that each got.

#1801 fix: typo in code comment (XLST)
  src/compiler/base/invoke-compiled/threads.xsl
Labels: bug

#1802 ci: codespell XLST
  test/ci/codespell-dic.txt
  test/ci/run-codespell.cmd
  test/ci/run-codespell.sh
Labels: test

#1776 fix(xquery): support whitespace in text value templates
  src/compiler/xquery/node-constructor/node-constructor.xsl
  test/avt-ws.xspec
  test/avt-ws_schematron.xspec
  test/avt-ws_stylesheet.xspec
  test/avt/detect-ws.xspec
  test/external_avt-ws_stylesheet.xspec
  test/external_tvt-ws_stylesheet.xspec
  test/tvt-ws.sch
  test/tvt-ws.xspec
  test/tvt-ws_schematron.xspec
  test/tvt-ws_stylesheet.xspec
  test/tvt/detect-ws.xspec
  test/tvt/shared-ws.xspec
Labels: bug

#1789 fix(schematron): make wrapper define $x:xspec-uri
  src/schematron/generate-step3-wrapper.xsl
  test/generate-step3-wrapper_custom.xspec
  test/generate-step3-wrapper_default.xspec
  test/schematron-global-xspec-uri.xspec
Labels: bug

#1794 docs(schema): inheritance of id from Schematron pattern
  src/schemas/xspec.rnc
Labels: documentation

#1814 feat(ant): xspec.force.focus=#none
  .commitlintrc.json
  CONTRIBUTING.md
  test/end-to-end/cases/expected/query/force-focus_none-junit.xml
  test/end-to-end/cases/expected/query/force-focus_none-result.html
  test/end-to-end/cases/expected/query/force-focus_none-result.xml
  test/end-to-end/cases/expected/schematron/force-focus_none-junit.xml
  test/end-to-end/cases/expected/schematron/force-focus_none-result.html
  test/end-to-end/cases/expected/schematron/force-focus_none-result.xml
  test/end-to-end/cases/expected/stylesheet/force-focus_none-junit.xml
  test/end-to-end/cases/expected/stylesheet/force-focus_none-result.html
  test/end-to-end/cases/expected/stylesheet/force-focus_none-result.xml
  test/end-to-end/cases/focus-without-pending.xspec
  test/end-to-end/cases/force-focus_none.xspec
Labels: enhancement, test
