Repository xspec/xspec, pull requests merged in 2024-01, with the labels that each got.

#1824 docs: namespace demo files for XSLT and XQuery
  test/tutorial_namespaces_query.xspec
  test/tutorial_namespaces_stylesheet.xspec
  tutorial/namespaces/namespace-demo.xqm
  tutorial/namespaces/namespace-demo.xsl
  tutorial/namespaces/namespace-demo_query.xspec
  tutorial/namespaces/namespace-demo_stylesheet.xspec
Labels: documentation

#1822 feat(schematron): allow verification of Schematron text
  src/schemas/xspec.rnc
  src/schematron/schut-to-xspec.xsl
  test/schematron-012.xspec
  test/schematron-text.xspec
  test/schematron/schematron-text.sch
  test/schematron/schut-to-xspec-012-out.xspec
Labels: enhancement

#1780 feat(xslt): runtime error if context evaluates to empty sequence
  src/compiler/xslt/compile/compile-scenario.xsl
  test/as_stylesheet.xspec
  test/bad-context/apply-templates/child-constant-select.xspec
  test/bad-context/apply-templates/child-variable-select.xspec
  test/bad-context/apply-templates/external_child-constant-select.xspec
  test/bad-context/apply-templates/href-broken.xspec
  test/bad-context/apply-templates/href-constant-select-inherited-augmented.xspec
  test/bad-context/apply-templates/href-constant-select-inherited.xspec
  test/bad-context/apply-templates/href-constant-select.xspec
  test/bad-context/apply-templates/href-variable-select.xspec
  test/bad-context/apply-templates/no-attr.xspec
  test/bad-context/apply-templates/select-only.xspec
  test/bad-context/call-template/child-constant-select.xspec
  test/bad-context/call-template/child-variable-select.xspec
  test/bad-context/call-template/external_child-constant-select.xspec
  test/bad-context/call-template/href-broken.xspec
  test/bad-context/call-template/href-constant-select-inherited-augmented.xspec
  test/bad-context/call-template/href-constant-select-inherited.xspec
  test/bad-context/call-template/href-constant-select.xspec
  test/bad-context/call-template/href-variable-select.xspec
  test/bad-context/call-template/no-attr.xspec
  test/bad-context/call-template/select-only.xspec
  test/compiler-eqname-utils.xspec
  test/end-to-end/cases/coverage_no-hit.xspec
  test/end-to-end/cases/expected/stylesheet/coverage_no-hit-result.xml
  test/end-to-end/cases/expected/stylesheet/external_issue-450-451_stylesheet-result.xml
  test/end-to-end/cases/expected/stylesheet/issue-450-451_stylesheet-result.xml
  test/end-to-end/cases/external_issue-450-451_stylesheet.xspec
  test/end-to-end/cases/issue-450-451_stylesheet.xspec
  test/error-compiling-scenario/function-with-context.xspec
  test/error-compiling-scenario/xquery_context.xspec
  test/external_as_stylesheet.xspec
  test/external_global-override.xsl
  test/external_global-override.xspec
  test/external_node-selection_stylesheet.xspec
  test/external_prefix-conflict_stylesheet.xspec
  test/external_undeclare-ns_stylesheet.xspec
  test/external_ws-only-text_stylesheet.xspec
  test/external_xml-base_stylesheet.xspec
  test/global-override.xsl
  test/global-override.xspec
  test/import/file-not-found.xspec
  test/import/no-href.xspec
  test/issue-987_child.xspec
  test/issue-987_parent.xspec
  test/namespace-vars.xspec
  test/node-selection_stylesheet.xspec
  test/prefix-conflict_stylesheet.xspec
  test/undeclare-ns_stylesheet.xspec
  test/version-utils.xspec
  test/win-bats/collection.xml
  test/win-bats/stub.cmd
  test/ws-only-text_stylesheet.xspec
  test/xml-base_stylesheet.xspec
  test/xspec.bats
Labels: enhancement

#1831 ci: check .properties style
  .prettierrc.json
  package-lock.json
  package.json
Labels: test

#1847 fix(schema): remove expand-text from x:like content model
  src/schemas/xspec.rnc
Labels: bug
