Repository xspec/xspec, pull requests merged in 2024-03, with the labels that each got.

#1871 ci(deps-dev): bump commitlint from 18.6.1 to 19.1.0
  package-lock.json
  package.json
Labels: dependencies, javascript

#1879 build(maven): use BC signer, with maven-gpg-plugin 3.2.0
  .github/workflows/maven-deploy.yml
Labels: github_actions

#1872 test: catalog usage with helper stylesheet
  test/catalog/01/helper.xqm
  test/catalog/01/helper.xsl
  test/catalog/01/imported.xspec
  test/catalog/catalog-01_query.xspec
  test/catalog/catalog-01_schematron.xspec
  test/catalog/catalog-01_stylesheet.xspec
  test/win-bats/collection.xml
  test/xspec.bats
Labels: test

#1876 fix: pending x:expect should not trigger running SUT
  src/compiler/base/compile/compile-child-scenarios-or-expects.xsl
  test/catch.xspec
  test/catch_stylesheet.xspec
  test/end-to-end/cases/expected/query/pending-junit.xml
  test/end-to-end/cases/expected/query/pending-result.html
  test/end-to-end/cases/expected/query/pending-result.xml
  test/end-to-end/cases/expected/schematron/pending-junit.xml
  test/end-to-end/cases/expected/schematron/pending-result.html
  test/end-to-end/cases/expected/schematron/pending-result.xml
  test/end-to-end/cases/expected/schematron/pending_schematron-result.xml
  test/end-to-end/cases/expected/stylesheet/pending-junit.xml
  test/end-to-end/cases/expected/stylesheet/pending-result.html
  test/end-to-end/cases/expected/stylesheet/pending-result.xml
  test/end-to-end/cases/pending.xspec
  test/win-bats/collection.xml
  test/xspec.bats
Labels: bug

#1842 feat: extend $x:context variable beyond x:expect
  src/compiler/base/compile/compile-child-scenarios-or-expects.xsl
  src/compiler/base/declare-variable/declare-variable.xsl
  src/compiler/base/invoke-compiled/invoke-compiled-child-scenarios-or-expects.xsl
  src/compiler/base/main.xsl
  src/compiler/xslt/compile/compile-scenario.xsl
  test/x-context.xspec
  tutorial/under-the-hood/Compilation.md
Labels: enhancement

#1885 docs: qualify comment about stylesheet not being testable
  tutorial/global-context-item/stylesheet_original.xsl
Labels: documentation

#1873 feat(schematron): allow variables in Schematron scenario
  src/schemas/xspec.rnc
  test/variable.sch
  test/variable.xspec
  test/variable_schematron.xspec
Labels: enhancement

#1838 feat: support ignoring attributes when comparing
  src/common/deep-equal.xqm
  src/common/deep-equal.xsl
  src/reporter/format-utils.xsl
  test/deep-equal.xspec
  test/end-to-end/cases/expected/query/three-dots-junit.xml
  test/end-to-end/cases/expected/query/three-dots-result.html
  test/end-to-end/cases/expected/query/three-dots-result.xml
  test/end-to-end/cases/expected/stylesheet/three-dots-junit.xml
  test/end-to-end/cases/expected/stylesheet/three-dots-result.html
  test/end-to-end/cases/expected/stylesheet/three-dots-result.xml
  test/end-to-end/cases/three-dots.xspec
Labels: enhancement

#1882 docs: indicate license for XSpec wiki
  CONTRIBUTING.md
  README.md
Labels: documentation

#1892 feat: support calling XPath function defined in variable
  src/compiler/base/combine/mode/check-combined-doc.xsl
  src/compiler/base/compile/compile-scenario.xsl
  src/schemas/xspec.rnc
  test/ant/worker/generate.xsl
  test/call-disallowed/external_function-in-variable.xspec
  test/function-in-variable.sch
  test/function-in-variable.xqm
  test/function-in-variable.xsl
  test/function-in-variable.xspec
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#1896 build(oxygen): add-on v3.0.1
  editors/oxygen/add-on/description/latest.xhtml
  oxygen-addon.xml
  xspec.xpr
Labels: release

#1833 feat(xslt): code coverage for Saxon 12.4+
  .github/dependabot.yml
  .github/workflows/test.yml
  appveyor.yml
  azure-pipelines.yml
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.class
  java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.java
  pom.xml
  src/reporter/coverage-report.xsl
  test/ant/worker/generate.xsl
  test/check-coverage-xml.xsl
  test/ci/azure-pipelines_windows.yml
  test/ci/compile-java.cmd
  test/ci/compile-java.sh
  test/ci/env/saxon-12.env
  test/ci/env/saxon-9-9.env
  test/ci/test-maven-jar.cmd
  test/ci/test-maven-jar.sh
  test/end-to-end/cases/expected/stylesheet/external_issue-1410_invoke-empty-result.xml
  test/end-to-end/cases/expected/stylesheet/external_issue-1410_invoke-not-empty-result.xml
  test/run-bats.cmd
  test/run-bats.sh
Labels: enhancement

#1891 feat: soft deprecate Saxon 10 through 12.3
  src/compiler/base/initial-check/perform-initial-check.xsl
  test/win-bats/collection.xml
  test/xspec.bats
Labels: enhancement

#1834 ci: remove Saxon 9.9 from CI matrix
  .github/workflows/test.yml
  test/ci/azure-pipelines_windows.yml
  test/ci/env/saxon-9-9.env
Labels: test

#1899 build(oxygen): add-on v3.0.2
  editors/oxygen/add-on/description/latest.xhtml
  oxygen-addon.xml
  xspec.xpr
Labels: release
